/**
 * Auto-generated Dataverse Type
 * Generated on: 2026-01-21T03:03:52.362Z
 * Table: aaduser
 * 
 * This file is automatically generated. Do not edit manually.
 */

import type { PsStaff, PsStaffSelect, PsStaffExpand } from './PsStaff.js'

/**
 * Microsoft Entra ID
 * Virtual entity that represents Microsoft Entra ID
 * 
 * Azure AD User - Microsoft Entra ID user accounts linked to staff members (PsStaff) for authentication and authorization.
 * 
 * RELATIONSHIPS:
 *   - ps_Manager[]: Related PsStaff records
 *   - ps_Entra[]: Related PsStaff records
 */
export interface Aaduser {
  // Primary Key
  aaduserid?: string

  // Yes/No Fields (Two Options)
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    accountenabled?: boolean | null

  // Reference Fields (Lookups)
  id?: string | null

  // Lookup Display Fields
  accountenabledname?: string | null
  companyname?: string | null
  displayname?: string | null
  givenname?: string | null
  surname?: string | null
  userprincipalname?: string | null

  // Other Fields
  businessphones?: string | null
  city?: string | null
  createddatetime?: string | null
  imaddresses?: string | null
  jobtitle?: string | null
  mail?: string | null
  mobilephone?: string | null
  officelocation?: string | null
  postalcode?: string | null
  preferredlanguage?: string | null
  streetaddress?: string | null
  usertype?: string | null

  // Relationships
  ps_Manager?: PsStaff[]
  ps_Entra?: PsStaff[]
}

export type AaduserEntitySet = 'aadusers'

export type AaduserCreate = Omit<Aaduser, 'aaduserid'>
export type AaduserUpdate = Partial<Omit<Aaduser, 'aaduserid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type AaduserSelect = keyof Aaduser
export type AaduserExpand = {
  ps_Manager?: {
    select?: PsStaffSelect[]
    expand?: PsStaffExpand
  }
  ps_Entra?: {
    select?: PsStaffSelect[]
    expand?: PsStaffExpand
  }
}


export const aaduserEntitySet: AaduserEntitySet = 'aadusers'
