/**
 * Auto-generated Dataverse Type
 * Generated on: 2026-01-21T03:03:52.361Z
 * Table: account
 * 
 * This file is automatically generated. Do not edit manually.
 */

import type { Salesorder, SalesorderSelect, SalesorderExpand } from './Salesorder.js'
import type { Product, ProductSelect, ProductExpand } from './Product.js'
import type { PsVehicledatabase, PsVehicledatabaseSelect, PsVehicledatabaseExpand } from './PsVehicledatabase.js'
import type { PsDeliveryroutes, PsDeliveryroutesSelect, PsDeliveryroutesExpand } from './PsDeliveryroutes.js'
import type { PsSetting, PsSettingSelect, PsSettingExpand } from './PsSetting.js'

/**
 * Account
 * Business that represents a customer or potential customer. The company that is billed in business transactions.
 * 
 * Account - Customers/clients who receive deliveries, and supplier accounts for purchase orders. Central entity linking purchases (PsPurchaseorder), deliveries (PsDeliveryroutes), and sales (Salesorder). Each account can have multiple delivery routes and sales orders.
 * 
 * RELATIONSHIPS:
 *   - msdyn_billingaccount_account[]: Related accounts
 *   - ps_Client[]: Related Salesorder records
 *   - ps_Supplier[]: Related Product records
 *   - ps_AssetManager[]: Related PsVehicledatabase records
 *   - accountparentaccount[]: Related accounts
 *   - msdyn_defaultvendor[]: Related Product records
 *   - msdyn_account[]: Related accounts
 *   - ps_account[]: Related accounts
 *   - msaaccountmanagingpartner[]: Related accounts
 *   - customerid_account[]: Related accounts
 *   - accountmasteraccount[]: Related accounts
 *   - ps_AccountClassification[]: Related PsSetting records
 *   - ps_RelationshipType[]: Related PsSetting records
 */
export interface Account {
  // Primary Key
  accountid?: string

  // Business Fields
  ps_accounttypename?: string
  ps_classification?: unknown
  ps_classificationname?: string
  ps_clientstatusguid?: string | null
  ps_clientstatusname?: string | null
  ps_clienttypename?: string
  ps_companylogo?: unknown
  ps_companylogo_timestamp?: number | null
  ps_companylogo_url?: string | null
  ps_industryname?: string | null
  ps_initiationdate?: string | null
  ps_languagename?: string | null
  ps_leadstagename?: string | null
  ps_logo?: unknown
  ps_logo_timestamp?: number | null
  ps_logo_url?: string | null
  ps_paymenttermsday?: number | null
  ps_paymenttermsname?: string | null
  ps_paymenttermsoptionname?: string
  ps_primarysitename?: string | null
  ps_rating?: number | null
  ps_ratingstar?: string | null
  ps_recordtypename?: string
  ps_relationshiptypechoicefield?: unknown
  ps_relationshiptypechoicefieldname?: string
  ps_searchtext?: string | null
  ps_sharepointfolder?: string | null
  ps_sharepointfolderid?: number | null
  ps_simproid?: number | null
  ps_simproidno?: number | null
  ps_simprojsonreference?: string | null
  ps_staffname?: string | null
  ps_usexeroforthisaccountname?: string
  ps_xerobalanceoutstanding?: number | null
  ps_xerobalanceoutstanding_base?: number | null
  ps_xerobalanceoverdue?: number | null
  ps_xerobalanceoverdue_base?: number | null
  ps_xeroid?: string | null
  ps_xerojsonreference?: string | null

  // Choice Fields (Option Sets)
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Preferred Customer
   * 2: Standard
   */
    accountcategorycode?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Default Value
   */
    accountclassificationcode?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: One
   * 2: Two
   * 3: Three
   * 4: Four
   * 5: Five
   */
    accountratingcode?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Bill To
   * 2: Ship To
   * 3: Primary
   * 4: Other
   */
    address1_addresstypecode?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: FOB
   * 2: No Charge
   */
    address1_freighttermscode?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Airborne
   * 2: DHL
   * 3: FedEx
   * 4: UPS
   * 5: Postal Mail
   * 6: Full Load
   * 7: Will Call
   */
    address1_shippingmethodcode?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Default Value
   */
    address2_addresstypecode?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Default Value
   */
    address2_freighttermscode?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Default Value
   */
    address2_shippingmethodcode?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Default Value
   */
    businesstypecode?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Default Value
   */
    customersizecode?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Competitor
   * 2: Consultant
   * 3: Customer
   * 4: Investor
   * 13: Insurance carrier
   * 5: Partner
   * 6: Influencer
   * 7: Press
   * 8: Prospect
   * 9: Reseller
   * 10: Supplier
   * 11: Vendor
   * 12: Other
   */
    customertypecode?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Accounting
   * 2: Agriculture and Non-petrol Natural Resource Extraction
   * 3: Broadcasting Printing and Publishing
   * 4: Brokers
   * 5: Building Supply Retail
   * 6: Business Services
   * 7: Consulting
   * 8: Consumer Services
   * 9: Design, Direction and Creative Management
   * 10: Distributors, Dispatchers and Processors
   * 11: Doctor's Offices and Clinics
   * 12: Durable Manufacturing
   * 13: Eating and Drinking Places
   * 14: Entertainment Retail
   * 15: Equipment Rental and Leasing
   * 16: Financial
   * 17: Food and Tobacco Processing
   * 18: Inbound Capital Intensive Processing
   * 19: Inbound Repair and Services
   * 20: Insurance
   * 21: Legal Services
   * 22: Non-Durable Merchandise Retail
   * 23: Outbound Consumer Service
   * 24: Petrochemical Extraction and Distribution
   * 25: Service Retail
   * 26: SIG Affiliations
   * 27: Social Services
   * 28: Special Outbound Trade Contractors
   * 29: Specialty Realty
   * 30: Transportation
   * 31: Utility Creation and Distribution
   * 32: Vehicle Retail
   * 33: Wholesale
   */
    industrycode?: number | null
  /**
   * Choice Field (Option Set)
   */
    msdyn_travelchargetype?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Public
   * 2: Private
   * 3: Subsidiary
   * 4: Other
   */
    ownershipcode?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Net 30
   * 2: 2% 10, Net 30
   * 3: Net 45
   * 4: Net 60
   */
    paymenttermscode?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 0: Sunday
   * 1: Monday
   * 2: Tuesday
   * 3: Wednesday
   * 4: Thursday
   * 5: Friday
   * 6: Saturday
   */
    preferredappointmentdaycode?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Morning
   * 2: Afternoon
   * 3: Evening
   */
    preferredappointmenttimecode?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Any
   * 2: Email
   * 3: Phone
   * 4: Fax
   * 5: Mail
   */
    preferredcontactmethodcode?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Individual
   * 2: Company
   */
    ps_accounttype?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Commercial
   * 2: Residential
   * 3: Government
   */
    ps_clienttype?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 125630000: of the following month
   * 125630001: day(s) after the invoice date
   * 125630002: day(s) after the invoice month
   * 125630003: of the current month
   */
    ps_paymenttermsoption?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 0: Lead
   * 1: Account
   */
    ps_recordtype?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Default Value
   */
    shippingmethodcode?: number | null
  /**
   * Choice Field (Option Set)
   */
    statecode?: number | null
  /**
   * Choice Field (Option Set)
   */
    statuscode?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Default Value
   */
    territorycode?: number | null

  // Yes/No Fields (Two Options)
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    creditonhold?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    donotbulkemail?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    donotbulkpostalmail?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    donotemail?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    donotfax?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    donotphone?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    donotpostalmail?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    donotsendmm?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    followemail?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    isprivate?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    marketingonly?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    merged?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    msdyn_gdproptout?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    msdyn_taxexempt?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    participatesinworkflow?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    ps_usexeroforthisaccount?: boolean | null

  // Reference Fields (Lookups)
  address1_addressid?: string | null
  address2_addressid?: string | null
  crd47_accountmanager?: string | null
  defaultpricelevelid?: string | null
  entityimageid?: string | null
  masterid?: string | null
  msa_managingpartnerid?: string | null
  msdyn_accountkpiid?: string | null
  msdyn_billingaccount?: string | null
  msdyn_preferredresource?: string | null
  msdyn_salesaccelerationinsightid?: string | null
  msdyn_salestaxcode?: string | null
  msdyn_segmentid?: string | null
  msdyn_serviceterritory?: string | null
  msdyn_workhourtemplate?: string | null
  originatingleadid?: string | null
  parentaccountid?: string | null
  preferredequipmentid?: string | null
  preferredserviceid?: string | null
  preferredsystemuserid?: string | null
  primarycontactid?: string | null
  processid?: string | null
  ps_clientstatus?: string | null
  ps_companylogoid?: string | null
  ps_industry?: string | null
  ps_language?: string | null
  ps_leadstage?: string | null
  ps_logoid?: string | null
  ps_paymentterms?: string | null
  ps_primarysite?: string | null
  ps_staff?: string | null
  slaid?: string | null
  slainvokedid?: string | null
  stageid?: string | null
  territoryid?: string | null
  transactioncurrencyid?: string | null

  // Lookup Display Fields
  accountcategorycodename?: string | null
  accountclassificationcodename?: string | null
  accountratingcodename?: string | null
  address1_addresstypecodename?: string | null
  address1_freighttermscodename?: string | null
  address1_name?: string | null
  address1_primarycontactname?: string | null
  address1_shippingmethodcodename?: string | null
  address2_addresstypecodename?: string | null
  address2_freighttermscodename?: string | null
  address2_name?: string | null
  address2_primarycontactname?: string | null
  address2_shippingmethodcodename?: string | null
  businesstypecodename?: string | null
  crd47_accountmanagername?: string | null
  crd47_sharepointname?: string | null
  crd47_shortname?: string | null
  creditonholdname?: string | null
  customersizecodename?: string | null
  customertypecodename?: string | null
  defaultpricelevelidname?: string | null
  donotbulkemailname?: string | null
  donotbulkpostalmailname?: string | null
  donotemailname?: string | null
  donotfaxname?: string | null
  donotphonename?: string | null
  donotpostalmailname?: string | null
  donotsendmarketingmaterialname?: string | null
  followemailname?: string | null
  industrycodename?: string | null
  isprivatename?: string | null
  marketingonlyname?: string | null
  masteraccountidname?: string | null
  masteraccountidyominame?: string | null
  mergedname?: string | null
  msa_managingpartneridname?: string | null
  msa_managingpartneridyominame?: string | null
  msdyn_accountkpiidname?: string | null
  msdyn_billingaccountname?: string | null
  msdyn_billingaccountyominame?: string | null
  msdyn_gdproptoutname?: string | null
  msdyn_preferredresourcename?: string | null
  msdyn_salesaccelerationinsightidname?: string | null
  msdyn_salestaxcodename?: string | null
  msdyn_segmentidname?: string | null
  msdyn_serviceterritoryname?: string | null
  msdyn_taxexemptname?: string | null
  msdyn_travelchargetypename?: string | null
  msdyn_workhourtemplatename?: string | null
  name?: string | null
  originatingleadidname?: string | null
  originatingleadidyominame?: string | null
  ownershipcodename?: string | null
  parentaccountidname?: string | null
  parentaccountidyominame?: string | null
  participatesinworkflowname?: string | null
  paymenttermscodename?: string | null
  preferredappointmentdaycodename?: string | null
  preferredappointmenttimecodename?: string | null
  preferredcontactmethodcodename?: string | null
  preferredequipmentidname?: string | null
  preferredserviceidname?: string | null
  preferredsystemuseridname?: string | null
  preferredsystemuseridyominame?: string | null
  primarycontactidname?: string | null
  primarycontactidyominame?: string | null
  shippingmethodcodename?: string | null
  slainvokedidname?: string | null
  slaname?: string | null
  statecodename?: string | null
  statuscodename?: string | null
  territorycodename?: string | null
  territoryidname?: string | null
  transactioncurrencyidname?: string | null
  yominame?: string | null

  // Audit Fields
  adx_createdbyipaddress?: string | null
  adx_createdbyusername?: string | null
  adx_modifiedbyipaddress?: string | null
  adx_modifiedbyusername?: string | null
  createdby?: string | null
  createdbyexternalparty?: string | null
  createdbyexternalpartyname?: string | null
  createdbyexternalpartyyominame?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyexternalparty?: string | null
  modifiedbyexternalpartyname?: string | null
  modifiedbyexternalpartyyominame?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null

  // Ownership Fields
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null

  // System Fields
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null

  // Other Fields
  accountnumber?: string | null
  address1_city?: string | null
  address1_composite?: string | null
  address1_country?: string | null
  address1_county?: string | null
  address1_fax?: string | null
  address1_latitude?: number | null
  address1_line1?: string | null
  address1_line2?: string | null
  address1_line3?: string | null
  address1_longitude?: number | null
  address1_postalcode?: string | null
  address1_postofficebox?: string | null
  address1_stateorprovince?: string | null
  address1_telephone1?: string | null
  address1_telephone2?: string | null
  address1_telephone3?: string | null
  address1_upszone?: string | null
  address1_utcoffset?: number | null
  address2_city?: string | null
  address2_composite?: string | null
  address2_country?: string | null
  address2_county?: string | null
  address2_fax?: string | null
  address2_latitude?: number | null
  address2_line1?: string | null
  address2_line2?: string | null
  address2_line3?: string | null
  address2_longitude?: number | null
  address2_postalcode?: string | null
  address2_postofficebox?: string | null
  address2_stateorprovince?: string | null
  address2_telephone1?: string | null
  address2_telephone2?: string | null
  address2_telephone3?: string | null
  address2_upszone?: string | null
  address2_utcoffset?: number | null
  aging30?: number | null
  aging30_base?: number | null
  aging60?: number | null
  aging60_base?: number | null
  aging90?: number | null
  aging90_base?: number | null
  crd47_abn?: string | null
  crd47_engagementdate?: string | null
  crd47_sharepointid?: number | null
  creditlimit?: number | null
  creditlimit_base?: number | null
  description?: string | null
  emailaddress1?: string | null
  emailaddress2?: string | null
  emailaddress3?: string | null
  entityimage?: unknown
  entityimage_timestamp?: number | null
  entityimage_url?: string | null
  exchangerate?: number | null
  fax?: string | null
  ftpsiteurl?: string | null
  lastonholdtime?: string | null
  lastusedincampaign?: string | null
  marketcap?: number | null
  marketcap_base?: number | null
  msdyn_primarytimezone?: number | null
  msdyn_taxexemptnumber?: string | null
  msdyn_travelcharge?: number | null
  msdyn_travelcharge_base?: number | null
  msdyn_workorderinstructions?: string | null
  numberofemployees?: number | null
  onholdtime?: number | null
  opendeals?: number | null
  opendeals_date?: string | null
  opendeals_state?: number | null
  openrevenue?: number | null
  openrevenue_base?: number | null
  openrevenue_date?: string | null
  openrevenue_state?: number | null
  primarysatoriid?: string | null
  primarytwitterid?: string | null
  revenue?: number | null
  revenue_base?: number | null
  sharesoutstanding?: number | null
  sic?: string | null
  stockexchange?: string | null
  teamsfollowed?: number | null
  telephone1?: string | null
  telephone2?: string | null
  telephone3?: string | null
  tickersymbol?: string | null
  timespentbymeonemailandmeetings?: string | null
  traversedpath?: string | null
  websiteurl?: string | null

  // Relationships
  msdyn_billingaccount_account?: Account[]
  ps_Client?: Salesorder[]
  ps_Supplier?: Product[]
  ps_AssetManager?: PsVehicledatabase[]
  accountparentaccount?: Account[]
  msdyn_defaultvendor?: Product[]
  msdyn_account?: Salesorder[]
  ps_account?: PsDeliveryroutes[]
  msaaccountmanagingpartner?: Account[]
  customerid_account?: Salesorder[]
  accountmasteraccount?: Account[]
  ps_AccountClassification?: PsSetting[]
  ps_RelationshipType?: PsSetting[]
}

export type AccountEntitySet = 'accounts'

export type AccountCreate = Omit<Account, 'accountid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type AccountUpdate = Partial<Omit<Account, 'accountid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type AccountSelect = keyof Account
export type AccountExpand = {
  msdyn_billingaccount_account?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  ps_Client?: {
    select?: SalesorderSelect[]
    expand?: SalesorderExpand
  }
  ps_Supplier?: {
    select?: ProductSelect[]
    expand?: ProductExpand
  }
  ps_AssetManager?: {
    select?: PsVehicledatabaseSelect[]
    expand?: PsVehicledatabaseExpand
  }
  accountparentaccount?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  msdyn_defaultvendor?: {
    select?: ProductSelect[]
    expand?: ProductExpand
  }
  msdyn_account?: {
    select?: SalesorderSelect[]
    expand?: SalesorderExpand
  }
  ps_account?: {
    select?: PsDeliveryroutesSelect[]
    expand?: PsDeliveryroutesExpand
  }
  msaaccountmanagingpartner?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  customerid_account?: {
    select?: SalesorderSelect[]
    expand?: SalesorderExpand
  }
  accountmasteraccount?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  ps_AccountClassification?: {
    select?: PsSettingSelect[]
    expand?: PsSettingExpand
  }
  ps_RelationshipType?: {
    select?: PsSettingSelect[]
    expand?: PsSettingExpand
  }
}


export const accountEntitySet: AccountEntitySet = 'accounts'
