/**
 * Auto-generated Dataverse Type
 * Generated on: 2026-01-21T03:03:52.360Z
 * Table: product
 * 
 * This file is automatically generated. Do not edit manually.
 */

import type { Salesorderdetail, SalesorderdetailSelect, SalesorderdetailExpand } from './Salesorderdetail.js'
import type { PsPurchaseorderline, PsPurchaseorderlineSelect, PsPurchaseorderlineExpand } from './PsPurchaseorderline.js'
import type { PsRelatedasset, PsRelatedassetSelect, PsRelatedassetExpand } from './PsRelatedasset.js'
import type { PsVehicledatabase, PsVehicledatabaseSelect, PsVehicledatabaseExpand } from './PsVehicledatabase.js'

/**
 * Product
 * Information about products and their pricing information.
 * 
 * Product - Catalog of products available for purchase and delivery. Includes inventory levels, supplier mappings (PsProductsuppliermapping), product specifications, and pricing. Products are ordered through purchase orders (PsPurchaseorder) and delivered via sales orders (Salesorder).
 * 
 * RELATIONSHIPS:
 *   - productorderdetails[]: Related Salesorderdetail records
 *   - ps_LineNumberProduct[]: Related products
 *   - ps_Product[]: Related products
 *   - productparentproduct[]: Related Product records
 *   - crd47_Name[]: Related PsVehicledatabase records
 */
export interface Product {
  // Primary Key
  productid?: string

  // Business Fields
  ps_characteristicsname?: string | null
  ps_formassetname?: string
  ps_formname?: string | null
  ps_inventorycategoryname?: string
  ps_labdatereceived?: string | null
  ps_labdatesent?: string | null
  ps_labresultname?: string
  ps_labresultnotes?: string | null
  ps_linenumber?: string | null
  ps_metricname?: string | null
  ps_minimumquantity?: number | null
  ps_productcategoryname?: string | null
  ps_purchaseorderlinename?: string | null
  ps_rackstandard?: number | null
  ps_remainingquantity?: number | null
  ps_sourcetypename?: string
  ps_suppliername?: string | null
  ps_supplieryominame?: string | null
  ps_trolleystandard?: number | null
  ps_trolleytall?: number | null

  // Choice Fields (Option Sets)
  /**
   * Choice Field (Option Set)
   * Options:
   * 232700000: Sydney Sprouts
   * 232700001: Bell Sprouts
   */
    crd47_entity?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 232700000: Per hour
   * 232700001: Per Unit
   * 232700002: Per Day
   * 232700003: Flat fee
   */
    crd47_minimumchargetype?: number | null
  /**
   * Choice Field (Option Set)
   */
    msdyn_fieldserviceproducttype?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Product
   * 2: Product Family
   * 3: Product Bundle
   */
    productstructure?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Sales Inventory
   * 2: Miscellaneous Charges
   * 3: Services
   * 4: Flat Fees
   */
    producttypecode?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 125630000: Raw Materials
   * 125630001: Sales Product
   * 125630002: Consumable Materials
   * 125630003: Service
   */
    ps_inventorycategory?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 125630000: Pending
   * 125630001: Passed
   * 125630002: Failed
   * 125630003: Not Sent
   */
    ps_labresult?: number | null
  /**
   * Choice Field (Option Set)
   */
    ps_sourcetype?: number | null
  /**
   * Choice Field (Option Set)
   */
    statecode?: number | null
  /**
   * Choice Field (Option Set)
   */
    statuscode?: number | null

  // Yes/No Fields (Two Options)
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    crd47_hasminimumcharge?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    iskit?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    isreparented?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    isstockitem?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    msdyn_converttocustomerasset?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    msdyn_gdproptout?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    msdyn_taxable?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    ps_formasset?: boolean | null

  // Reference Fields (Lookups)
  defaultuomid?: string | null
  defaultuomscheduleid?: string | null
  entityimageid?: string | null
  msdyn_defaultvendor?: string | null
  organizationid?: string | null
  parentproductid?: string | null
  pricelevelid?: string | null
  processid?: string | null
  ps_characteristics?: string | null
  ps_form?: string | null
  ps_metric?: string | null
  ps_productcategory?: string | null
  ps_purchaseorderline?: string | null
  ps_supplier?: string | null
  stageid?: string | null
  subjectid?: string | null
  transactioncurrencyid?: string | null

  // Lookup Display Fields
  crd47_entityname?: string | null
  crd47_hasminimumchargename?: string | null
  crd47_minimumchargetypename?: string | null
  defaultuomidname?: string | null
  defaultuomscheduleidname?: string | null
  iskitname?: string | null
  isreparentedname?: string | null
  isstockitemname?: string | null
  msdyn_converttocustomerassetname?: string | null
  msdyn_defaultvendorname?: string | null
  msdyn_defaultvendoryominame?: string | null
  msdyn_fieldserviceproducttypename?: string | null
  msdyn_gdproptoutname?: string | null
  msdyn_purchasename?: string | null
  msdyn_taxablename?: string | null
  name?: string | null
  organizationidname?: string | null
  parentproductidname?: string | null
  pricelevelidname?: string | null
  productstructurename?: string | null
  producttypecodename?: string | null
  statecodename?: string | null
  statuscodename?: string | null
  subjectidname?: string | null
  suppliername?: string | null
  transactioncurrencyidname?: string | null
  vendorname?: string | null

  // Audit Fields
  createdby?: string | null
  createdbyexternalparty?: string | null
  createdbyexternalpartyname?: string | null
  createdbyexternalpartyyominame?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyexternalparty?: string | null
  modifiedbyexternalpartyname?: string | null
  modifiedbyexternalpartyyominame?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null

  // System Fields
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null

  // Other Fields
  crd47_hasminimumchargeamount?: number | null
  currentcost?: number | null
  currentcost_base?: number | null
  description?: string | null
  dmtimportstate?: number | null
  entityimage?: unknown
  entityimage_timestamp?: number | null
  entityimage_url?: string | null
  exchangerate?: number | null
  hierarchypath?: string | null
  msdyn_alsoknownas?: string | null
  msdyn_scopes?: string | null
  msdyn_upccode?: string | null
  price?: number | null
  price_base?: number | null
  productnumber?: string | null
  producturl?: string | null
  quantitydecimal?: number | null
  quantityonhand?: number | null
  size?: string | null
  standardcost?: number | null
  standardcost_base?: number | null
  stockvolume?: number | null
  stockweight?: number | null
  traversedpath?: string | null
  validfromdate?: string | null
  validtodate?: string | null
  vendorid?: string | null
  vendorpartnumber?: string | null

  // Relationships
  productorderdetails?: Salesorderdetail[]
  ps_LineNumberProduct?: PsPurchaseorderline[]
  ps_Product?: PsRelatedasset[]
  productparentproduct?: Product[]
  crd47_Name?: PsVehicledatabase[]
}

export type ProductEntitySet = 'products'

export type ProductCreate = Omit<Product, 'productid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby'>
export type ProductUpdate = Partial<Omit<Product, 'productid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type ProductSelect = keyof Product
export type ProductExpand = {
  productorderdetails?: {
    select?: SalesorderdetailSelect[]
    expand?: SalesorderdetailExpand
  }
  ps_LineNumberProduct?: {
    select?: PsPurchaseorderlineSelect[]
    expand?: PsPurchaseorderlineExpand
  }
  ps_Product?: {
    select?: PsRelatedassetSelect[]
    expand?: PsRelatedassetExpand
  }
  productparentproduct?: {
    select?: ProductSelect[]
    expand?: ProductExpand
  }
  crd47_Name?: {
    select?: PsVehicledatabaseSelect[]
    expand?: PsVehicledatabaseExpand
  }
}


export const productEntitySet: ProductEntitySet = 'products'
