/**
 * Auto-generated Dataverse Type
 * Generated on: 2026-01-21T03:03:52.361Z
 * Table: ps_appfeature
 * 
 * This file is automatically generated. Do not edit manually.
 */

/**
 * App Feature
 * Application Feature - Feature flags and application configuration.
 */
export interface PsAppfeature {
  // Primary Key
  ps_appfeatureid?: string

  // Business Fields
  ps_appcode?: string | null
  ps_enabledname?: string
  ps_featuretype?: string | null
  ps_name?: string | null

  // Choice Fields (Option Sets)
  /**
   * Choice Field (Option Set)
   */
    statecode?: number | null
  /**
   * Choice Field (Option Set)
   */
    statuscode?: number | null

  // Yes/No Fields (Two Options)
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    ps_enabled?: boolean | null

  // Lookup Display Fields
  statecodename?: string | null
  statuscodename?: string | null

  // Audit Fields
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null

  // Ownership Fields
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null

  // System Fields
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null}

export type PsAppfeatureEntitySet = 'ps_appfeatures'

export type PsAppfeatureCreate = Omit<PsAppfeature, 'ps_appfeatureid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsAppfeatureUpdate = Partial<Omit<PsAppfeature, 'ps_appfeatureid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsAppfeatureSelect = keyof PsAppfeature
export type PsAppfeatureExpand = Record<string, never>


export const psappfeatureEntitySet: PsAppfeatureEntitySet = 'ps_appfeatures'
