/**
 * Auto-generated Dataverse Type
 * Generated on: 2026-01-21T03:03:52.355Z
 * Table: ps_deliveryroutes
 * 
 * This file is automatically generated. Do not edit manually.
 */

import type { Salesorder, SalesorderSelect, SalesorderExpand } from './Salesorder.js'

/**
 * Delivery Routes
 * Delivery Route - Represents a scheduled delivery stop/route in the delivery system. Links customer accounts (Account), drivers (PsStaff), vehicles (PsVehicledatabase), and sales orders (Salesorder) for route optimization and tracking. Each route has planned/actual times, sequence, location coordinates, and capacity usage.
 * 
 * RELATIONSHIPS:
 *   - ps_deliveryroute[]: Sales orders linked to this delivery route
 */
export interface PsDeliveryroutes {
  // Primary Key
  ps_deliveryroutesid?: string

  // Business Fields
  ps_account_name?: string | null
  ps_accountname?: string | null
  ps_accountyominame?: string | null
  ps_actualdeliverytime?: string | null
  ps_actualendtime?: string | null
  ps_actualstarttime?: string | null
  ps_address?: string | null
  ps_capacityusage?: number | null
  ps_contactname?: string | null
  ps_contactphone?: string | null
  ps_delivered_by_name?: string | null
  ps_deliveredbyname?: string | null
  ps_deliveryconfirmationstatusname?: string
  ps_driver_name?: string | null
  ps_drivername?: string | null
  ps_drivernotes?: string | null
  ps_estimateddistance?: number | null
  ps_estimatedduration?: number | null
  ps_hasphotoname?: string
  ps_orderpriorityname?: string
  ps_plannedendtime?: string | null
  ps_plannedstarttime?: string | null
  ps_route_date?: string | null
  ps_routegroupid?: string | null
  ps_routename?: string | null
  ps_sequence?: number | null
  ps_sitelat?: number | null
  ps_sitelong?: number | null
  ps_territorygroupname?: string | null
  ps_vehicle_routename?: string | null
  ps_vehiclename?: string | null

  // Choice Fields (Option Sets)
  /**
   * Choice Field (Option Set)
   */
    ps_deliveryconfirmationstatus?: number | null
  /**
   * Choice Field (Option Set)
   */
    ps_orderpriority?: number | null
  /**
   * Choice Field (Option Set)
   */
    statecode?: number | null
  /**
   * Choice Field (Option Set)
   */
    statuscode?: number | null

  // Yes/No Fields (Two Options)
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    ps_hasphoto?: boolean | null

  // Reference Fields (Lookups)
  ps_account?: string | null
  ps_deliveredby?: string | null
  ps_driver?: string | null
  ps_territorygroup?: string | null
  ps_vehicle_route?: string | null

  // Lookup Display Fields
  statecodename?: string | null
  statuscodename?: string | null

  // Audit Fields
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null

  // Ownership Fields
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null

  // System Fields
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null

  // Relationships
  ps_deliveryroute?: Salesorder[]
}

export type PsDeliveryroutesEntitySet = 'ps_deliveryrouteses'

export type PsDeliveryroutesCreate = Omit<PsDeliveryroutes, 'ps_deliveryroutesid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsDeliveryroutesUpdate = Partial<Omit<PsDeliveryroutes, 'ps_deliveryroutesid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsDeliveryroutesSelect = keyof PsDeliveryroutes
export type PsDeliveryroutesExpand = {
  ps_deliveryroute?: {
    select?: SalesorderSelect[]
    expand?: SalesorderExpand
  }
}


export const psdeliveryroutesEntitySet: PsDeliveryroutesEntitySet = 'ps_deliveryrouteses'
