/**
 * Auto-generated Dataverse Type
 * Generated on: 2026-01-21T03:03:52.355Z
 * Table: ps_deliveryschedule
 * 
 * This file is automatically generated. Do not edit manually.
 */

/**
 * Delivery Schedule
 * Delivery Schedule - Defines delivery schedules and territories for managing recurring delivery routes and route assignments.
 */
export interface PsDeliveryschedule {
  // Primary Key
  ps_deliveryscheduleid?: string

  // Business Fields
  ps_date?: string | null
  ps_id?: string | null
  ps_operatorname?: string | null
  ps_orderterritoryname?: string | null
  ps_territorygroupname?: string | null
  ps_territorytypename?: string
  ps_time?: string | null
  ps_vehiclename?: string | null

  // Choice Fields (Option Sets)
  /**
   * Choice Field (Option Set)
   * Options:
   * 125630000: Territory Management App
   * 125630001: Order Territory
   */
    ps_territorytype?: number | null
  /**
   * Choice Field (Option Set)
   */
    statecode?: number | null
  /**
   * Choice Field (Option Set)
   */
    statuscode?: number | null

  // Reference Fields (Lookups)
  ps_operator?: string | null
  ps_orderterritory?: string | null
  ps_territorygroup?: string | null
  ps_vehicle?: string | null

  // Lookup Display Fields
  statecodename?: string | null
  statuscodename?: string | null

  // Audit Fields
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null

  // Ownership Fields
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null

  // System Fields
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null}

export type PsDeliveryscheduleEntitySet = 'ps_deliveryschedules'

export type PsDeliveryscheduleCreate = Omit<PsDeliveryschedule, 'ps_deliveryscheduleid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsDeliveryscheduleUpdate = Partial<Omit<PsDeliveryschedule, 'ps_deliveryscheduleid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsDeliveryscheduleSelect = keyof PsDeliveryschedule
export type PsDeliveryscheduleExpand = Record<string, never>


export const psdeliveryscheduleEntitySet: PsDeliveryscheduleEntitySet = 'ps_deliveryschedules'
