/**
 * Auto-generated Dataverse Type
 * Generated on: 2026-01-21T03:03:52.356Z
 * Table: ps_jobassetattachment
 * 
 * This file is automatically generated. Do not edit manually.
 */

/**
 * Job Asset Attachment
 * Job Asset Attachment - Attachments and assets related to delivery jobs and schedules.
 */
export interface PsJobassetattachment {
  // Primary Key
  ps_jobassetattachmentid?: string

  // Business Fields
  ps_assetnickname?: string | null
  ps_attachmentid?: string | null
  ps_attachmentname?: string | null
  ps_id?: string | null
  ps_jobscheduledate?: string | null
  ps_jobschedulename?: string | null

  // Choice Fields (Option Sets)
  /**
   * Choice Field (Option Set)
   */
    statecode?: number | null
  /**
   * Choice Field (Option Set)
   */
    statuscode?: number | null

  // Reference Fields (Lookups)
  ps_attachment?: string | null
  ps_jobschedule?: string | null

  // Lookup Display Fields
  statecodename?: string | null
  statuscodename?: string | null

  // Audit Fields
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null

  // Ownership Fields
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null

  // System Fields
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null}

export type PsJobassetattachmentEntitySet = 'ps_jobassetattachments'

export type PsJobassetattachmentCreate = Omit<PsJobassetattachment, 'ps_jobassetattachmentid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsJobassetattachmentUpdate = Partial<Omit<PsJobassetattachment, 'ps_jobassetattachmentid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsJobassetattachmentSelect = keyof PsJobassetattachment
export type PsJobassetattachmentExpand = Record<string, never>


export const psjobassetattachmentEntitySet: PsJobassetattachmentEntitySet = 'ps_jobassetattachments'
