/**
 * Auto-generated Dataverse Type
 * Generated on: 2026-01-21T03:03:52.362Z
 * Table: ps_joblist
 * 
 * This file is automatically generated. Do not edit manually.
 */

import type { PsPurchaseorder, PsPurchaseorderSelect, PsPurchaseorderExpand } from './PsPurchaseorder.js'

/**
 * Job List
 * Job List - List of delivery jobs/work orders that need to be scheduled and routed. Jobs are assigned to delivery routes.
 * 
 * RELATIONSHIPS:
 *   - ps_Job[]: Related PsPurchaseorder records
 */
export interface PsJoblist {
  // Primary Key
  ps_joblistid?: string

  // Business Fields
  ps_clientcontactname?: string | null
  ps_clientcontactyominame?: string | null
  ps_clientname?: string | null
  ps_clientyominame?: string | null
  ps_completeddatetime?: string | null
  ps_currencyname?: string | null
  ps_defaultendtime?: string | null
  ps_defaultstarttime?: string | null
  ps_enddatetime?: string | null
  ps_fillvalue?: string | null
  ps_folderurl?: string | null
  ps_id?: string | null
  ps_jobdescription?: string | null
  ps_jobnotescomments?: string | null
  ps_jobstatusname?: string | null
  ps_jobtitle?: string | null
  ps_jobtypename?: string | null
  ps_managername?: string | null
  ps_ordernumber1?: string | null
  ps_ordernumber2?: string | null
  ps_ordernumber3?: string | null
  ps_pricelistname?: string | null
  ps_quotename?: string | null
  ps_salespersonname?: string | null
  ps_simproid?: number | null
  ps_singlesitename?: string
  ps_sitename?: string | null
  ps_startdatetime?: string | null

  // Choice Fields (Option Sets)
  /**
   * Choice Field (Option Set)
   */
    crd47_jobsetup?: number | null
  /**
   * Choice Field (Option Set)
   */
    statecode?: number | null
  /**
   * Choice Field (Option Set)
   */
    statuscode?: number | null

  // Yes/No Fields (Two Options)
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    ps_singlesite?: boolean | null

  // Reference Fields (Lookups)
  ps_client?: string | null
  ps_clientcontact?: string | null
  ps_currency?: string | null
  ps_jobstatus?: string | null
  ps_jobtype?: string | null
  ps_manager?: string | null
  ps_pricelist?: string | null
  ps_quote?: string | null
  ps_salesperson?: string | null
  ps_site?: string | null

  // Lookup Display Fields
  crd47_jobsetupname?: string | null
  statecodename?: string | null
  statuscodename?: string | null

  // Audit Fields
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null

  // Ownership Fields
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null

  // System Fields
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null

  // Relationships
  ps_Job?: PsPurchaseorder[]
}

export type PsJoblistEntitySet = 'ps_joblists'

export type PsJoblistCreate = Omit<PsJoblist, 'ps_joblistid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsJoblistUpdate = Partial<Omit<PsJoblist, 'ps_joblistid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsJoblistSelect = keyof PsJoblist
export type PsJoblistExpand = {
  ps_Job?: {
    select?: PsPurchaseorderSelect[]
    expand?: PsPurchaseorderExpand
  }
}


export const psjoblistEntitySet: PsJoblistEntitySet = 'ps_joblists'
