/**
 * Auto-generated Dataverse Type
 * Generated on: 2026-01-21T03:03:52.363Z
 * Table: ps_poreportgenerationrequest
 * 
 * This file is automatically generated. Do not edit manually.
 */

/**
 * PO Report Generation Request
 * PO Report Generation Request - Request to generate purchase order reports.
 */
export interface PsPoreportgenerationrequest {
  // Primary Key
  ps_poreportgenerationrequestid?: string

  // Business Fields
  ps_folderlocationurl?: string | null
  ps_foldername?: string | null
  ps_name?: string | null
  ps_pdf?: unknown
  ps_pdf_name?: string | null
  ps_pdffileurl?: string | null
  ps_poguid?: string | null
  ps_pono?: string | null
  ps_reportstatusname?: string
  ps_reporttype?: string | null
  ps_wordfileurl?: string | null

  // Choice Fields (Option Sets)
  /**
   * Choice Field (Option Set)
   * Options:
   * 125630000: In Progress
   * 125630001: Completed
   */
    ps_reportstatus?: number | null
  /**
   * Choice Field (Option Set)
   */
    statecode?: number | null
  /**
   * Choice Field (Option Set)
   */
    statuscode?: number | null

  // Lookup Display Fields
  statecodename?: string | null
  statuscodename?: string | null

  // Audit Fields
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null

  // Ownership Fields
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null

  // System Fields
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null}

export type PsPoreportgenerationrequestEntitySet = 'ps_poreportgenerationrequests'

export type PsPoreportgenerationrequestCreate = Omit<PsPoreportgenerationrequest, 'ps_poreportgenerationrequestid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsPoreportgenerationrequestUpdate = Partial<Omit<PsPoreportgenerationrequest, 'ps_poreportgenerationrequestid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsPoreportgenerationrequestSelect = keyof PsPoreportgenerationrequest
export type PsPoreportgenerationrequestExpand = Record<string, never>


export const psporeportgenerationrequestEntitySet: PsPoreportgenerationrequestEntitySet = 'ps_poreportgenerationrequests'
