/**
 * Auto-generated Dataverse Type
 * Generated on: 2026-01-21T03:03:52.358Z
 * Table: ps_postalareaboundary
 * 
 * This file is automatically generated. Do not edit manually.
 */

/**
 * Postal Area Boundary
 * Postal Area Boundary - Geographic boundaries for postal/territory management in routing and territory assignment.
 */
export interface PsPostalareaboundary {
  // Primary Key
  ps_postalareaboundaryid?: string

  // Business Fields
  ps_assignedterritorygroupname?: string | null
  ps_color?: string | null
  ps_geojson?: string | null
  ps_id?: string | null
  ps_latitude?: number | null
  ps_longitude?: number | null
  ps_postcode?: string | null
  ps_territorygroupcolor?: string | null

  // Choice Fields (Option Sets)
  /**
   * Choice Field (Option Set)
   */
    statecode?: number | null
  /**
   * Choice Field (Option Set)
   */
    statuscode?: number | null

  // Reference Fields (Lookups)
  ps_assignedterritorygroup?: string | null

  // Lookup Display Fields
  statecodename?: string | null
  statuscodename?: string | null

  // Audit Fields
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null

  // Ownership Fields
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null

  // System Fields
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null}

export type PsPostalareaboundaryEntitySet = 'ps_postalareaboundaries'

export type PsPostalareaboundaryCreate = Omit<PsPostalareaboundary, 'ps_postalareaboundaryid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsPostalareaboundaryUpdate = Partial<Omit<PsPostalareaboundary, 'ps_postalareaboundaryid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsPostalareaboundarySelect = keyof PsPostalareaboundary
export type PsPostalareaboundaryExpand = Record<string, never>


export const pspostalareaboundaryEntitySet: PsPostalareaboundaryEntitySet = 'ps_postalareaboundaries'
