/**
 * Auto-generated Dataverse Type
 * Generated on: 2026-01-21T03:03:52.364Z
 * Table: ps_productsuppliermapping
 * 
 * This file is automatically generated. Do not edit manually.
 */

/**
 * Product Supplier Mapping
 * Product Supplier Mapping - Maps products (Product) to suppliers (Account) for automated purchase order creation. When inventory is low, the system can automatically create purchase orders to the mapped supplier.
 */
export interface PsProductsuppliermapping {
  // Primary Key
  ps_productsuppliermappingid?: string

  // Business Fields
  ps_productcode?: string | null
  ps_productname?: string | null

  // Choice Fields (Option Sets)
  /**
   * Choice Field (Option Set)
   */
    statecode?: number | null
  /**
   * Choice Field (Option Set)
   */
    statuscode?: number | null

  // Reference Fields (Lookups)
  ps_product?: string | null

  // Lookup Display Fields
  statecodename?: string | null
  statuscodename?: string | null

  // Audit Fields
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null

  // Ownership Fields
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null

  // System Fields
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null}

export type PsProductsuppliermappingEntitySet = 'ps_productsuppliermappings'

export type PsProductsuppliermappingCreate = Omit<PsProductsuppliermapping, 'ps_productsuppliermappingid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsProductsuppliermappingUpdate = Partial<Omit<PsProductsuppliermapping, 'ps_productsuppliermappingid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsProductsuppliermappingSelect = keyof PsProductsuppliermapping
export type PsProductsuppliermappingExpand = Record<string, never>


export const psproductsuppliermappingEntitySet: PsProductsuppliermappingEntitySet = 'ps_productsuppliermappings'
