/**
 * Auto-generated Dataverse Type
 * Generated on: 2026-01-21T03:03:52.365Z
 * Table: ps_purchaseorder
 * 
 * This file is automatically generated. Do not edit manually.
 */

import type { PsPurchaseorderline, PsPurchaseorderlineSelect, PsPurchaseorderlineExpand } from './PsPurchaseorderline.js'

/**
 * Purchase Order
 * Purchase Order - Orders from suppliers to restock inventory. Links to suppliers (Account via ps_supplier), products (via PsPurchaseorderline), jobs (ps_job), and approvers (PsStaff). Tracks total amounts, approval status, and receipt status.
 * 
 * RELATIONSHIPS:
 *   - ps_PurchaseOrder[]: Purchase order line items
 */
export interface PsPurchaseorder {
  // Primary Key
  ps_purchaseorderid?: string

  // Business Fields
  ps_approvaldate?: string | null
  ps_approvercomment?: string | null
  ps_approvername?: string | null
  ps_client?: string | null
  ps_daterequired?: string | null
  ps_internalnotes?: string | null
  ps_jobname?: string | null
  ps_location?: string | null
  ps_name?: string | null
  ps_notes?: string | null
  ps_ponotes?: string | null
  ps_suppliername?: string | null
  ps_supplieryominame?: string | null
  ps_totalamount?: number | null
  ps_totalamount_base?: number | null
  ps_totalreceivedamount?: number | null
  ps_totalreceivedamount_base?: number | null
  ps_urgencyname?: string

  // Choice Fields (Option Sets)
  /**
   * Choice Field (Option Set)
   */
    ps_urgency?: number | null
  /**
   * Choice Field (Option Set)
   */
    statecode?: number | null
  /**
   * Choice Field (Option Set)
   */
    statuscode?: number | null

  // Reference Fields (Lookups)
  ps_approver?: string | null
  ps_job?: string | null
  ps_supplier?: string | null
  transactioncurrencyid?: string | null

  // Lookup Display Fields
  statecodename?: string | null
  statuscodename?: string | null
  transactioncurrencyidname?: string | null

  // Audit Fields
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null

  // Ownership Fields
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null

  // System Fields
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null

  // Other Fields
  exchangerate?: number | null

  // Relationships
  ps_PurchaseOrder?: PsPurchaseorderline[]
}

export type PsPurchaseorderEntitySet = 'ps_purchaseorders'

export type PsPurchaseorderCreate = Omit<PsPurchaseorder, 'ps_purchaseorderid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsPurchaseorderUpdate = Partial<Omit<PsPurchaseorder, 'ps_purchaseorderid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsPurchaseorderSelect = keyof PsPurchaseorder
export type PsPurchaseorderExpand = {
  ps_PurchaseOrder?: {
    select?: PsPurchaseorderlineSelect[]
    expand?: PsPurchaseorderlineExpand
  }
}


export const pspurchaseorderEntitySet: PsPurchaseorderEntitySet = 'ps_purchaseorders'
