/**
 * Auto-generated Dataverse Type
 * Generated on: 2026-01-21T03:03:52.365Z
 * Table: ps_purchaseorderreceiptline
 * 
 * This file is automatically generated. Do not edit manually.
 */

/**
 * Purchase Order Receipt Line
 * Purchase Order Receipt Line - Line items in a purchase order receipt (PsPurchaseorderreceipt), detailing what quantities were actually received for each product.
 */
export interface PsPurchaseorderreceiptline {
  // Primary Key
  ps_purchaseorderreceiptlineid?: string

  // Business Fields
  ps_polineid?: string | null
  ps_polinename?: string | null
  ps_purchaseorderlinename?: string | null
  ps_purchaseorderreceiptname?: string | null
  ps_quantityreceived?: number | null

  // Choice Fields (Option Sets)
  /**
   * Choice Field (Option Set)
   */
    statecode?: number | null
  /**
   * Choice Field (Option Set)
   */
    statuscode?: number | null

  // Reference Fields (Lookups)
  ps_poline?: string | null
  ps_purchaseorderline?: string | null
  ps_purchaseorderreceipt?: string | null

  // Lookup Display Fields
  statecodename?: string | null
  statuscodename?: string | null

  // Audit Fields
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null

  // Ownership Fields
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null

  // System Fields
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null}

export type PsPurchaseorderreceiptlineEntitySet = 'ps_purchaseorderreceiptlines'

export type PsPurchaseorderreceiptlineCreate = Omit<PsPurchaseorderreceiptline, 'ps_purchaseorderreceiptlineid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsPurchaseorderreceiptlineUpdate = Partial<Omit<PsPurchaseorderreceiptline, 'ps_purchaseorderreceiptlineid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsPurchaseorderreceiptlineSelect = keyof PsPurchaseorderreceiptline
export type PsPurchaseorderreceiptlineExpand = Record<string, never>


export const pspurchaseorderreceiptlineEntitySet: PsPurchaseorderreceiptlineEntitySet = 'ps_purchaseorderreceiptlines'
