/**
 * Auto-generated Dataverse Type
 * Generated on: 2026-01-21T03:03:52.365Z
 * Table: ps_purchaseorderline
 * 
 * This file is automatically generated. Do not edit manually.
 */

import type { Product, ProductSelect, ProductExpand } from './Product.js'
import type { PsPurchaseorderreceiptline, PsPurchaseorderreceiptlineSelect, PsPurchaseorderreceiptlineExpand } from './PsPurchaseorderreceiptline.js'

/**
 * Purchase Order Line
 * Purchase Order Line - Line items in a purchase order (PsPurchaseorder), specifying products (Product) and quantities to purchase. Each line links to a product and includes quantity and pricing information.
 * 
 * RELATIONSHIPS:
 *   - ps_ParentPurchaseOrderLine[]: Purchase order line items
 *   - ps_PurchaseOrderLine[]: Purchase order line items
 *   - ps_POLine[]: Related PsPurchaseorderreceiptline records
 */
export interface PsPurchaseorderline {
  // Primary Key
  ps_purchaseorderlineid?: string

  // Business Fields
  ps_linenumber?: string | null
  ps_linenumberproductname?: string | null
  ps_name?: string | null
  ps_parentpurchaseorderlinename?: string | null
  ps_price?: number | null
  ps_price_base?: number | null
  ps_productname?: string | null
  ps_purchaseordername?: string | null
  ps_quantity?: number | null
  ps_quantitypendingreceipt?: number | null
  ps_quantityreceived?: number | null
  ps_totalamount?: number | null
  ps_totalamount_base?: number | null
  ps_totalreceivedamount?: number | null
  ps_totalreceivedamount_base?: number | null

  // Choice Fields (Option Sets)
  /**
   * Choice Field (Option Set)
   */
    statecode?: number | null
  /**
   * Choice Field (Option Set)
   */
    statuscode?: number | null

  // Reference Fields (Lookups)
  ps_linenumberproduct?: string | null
  ps_parentpurchaseorderline?: string | null
  ps_product?: string | null
  ps_purchaseorder?: string | null
  transactioncurrencyid?: string | null

  // Lookup Display Fields
  statecodename?: string | null
  statuscodename?: string | null
  transactioncurrencyidname?: string | null

  // Audit Fields
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null

  // Ownership Fields
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null

  // System Fields
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null

  // Other Fields
  exchangerate?: number | null

  // Relationships
  ps_ParentPurchaseOrderLine?: PsPurchaseorderline[]
  ps_PurchaseOrderLine?: Product[]
  ps_POLine?: PsPurchaseorderreceiptline[]
}

export type PsPurchaseorderlineEntitySet = 'ps_purchaseorderlines'

export type PsPurchaseorderlineCreate = Omit<PsPurchaseorderline, 'ps_purchaseorderlineid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsPurchaseorderlineUpdate = Partial<Omit<PsPurchaseorderline, 'ps_purchaseorderlineid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsPurchaseorderlineSelect = keyof PsPurchaseorderline
export type PsPurchaseorderlineExpand = {
  ps_ParentPurchaseOrderLine?: {
    select?: PsPurchaseorderlineSelect[]
    expand?: PsPurchaseorderlineExpand
  }
  ps_PurchaseOrderLine?: {
    select?: ProductSelect[]
    expand?: ProductExpand
  }
  ps_POLine?: {
    select?: PsPurchaseorderreceiptlineSelect[]
    expand?: PsPurchaseorderreceiptlineExpand
  }
}


export const pspurchaseorderlineEntitySet: PsPurchaseorderlineEntitySet = 'ps_purchaseorderlines'
