/**
 * Auto-generated Dataverse Type
 * Generated on: 2026-01-21T03:03:52.365Z
 * Table: ps_purchaseorderreceipt
 * 
 * This file is automatically generated. Do not edit manually.
 */

import type { PsPurchaseorderreceiptline, PsPurchaseorderreceiptlineSelect, PsPurchaseorderreceiptlineExpand } from './PsPurchaseorderreceiptline.js'

/**
 * Purchase Order Receipt
 * Purchase Order Receipt - Receipt records for received purchase orders, tracking what was actually received vs what was ordered. Links to the original purchase order (PsPurchaseorder).
 * 
 * RELATIONSHIPS:
 *   - ps_PurchaseOrderReceipt[]: Purchase order line items
 */
export interface PsPurchaseorderreceipt {
  // Primary Key
  ps_purchaseorderreceiptid?: string

  // Business Fields
  ps_purchaseordername?: string | null
  ps_receiptid?: string | null

  // Choice Fields (Option Sets)
  /**
   * Choice Field (Option Set)
   */
    statecode?: number | null
  /**
   * Choice Field (Option Set)
   */
    statuscode?: number | null

  // Reference Fields (Lookups)
  ps_purchaseorder?: string | null

  // Lookup Display Fields
  statecodename?: string | null
  statuscodename?: string | null

  // Audit Fields
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null

  // Ownership Fields
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null

  // System Fields
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null

  // Relationships
  ps_PurchaseOrderReceipt?: PsPurchaseorderreceiptline[]
}

export type PsPurchaseorderreceiptEntitySet = 'ps_purchaseorderreceipts'

export type PsPurchaseorderreceiptCreate = Omit<PsPurchaseorderreceipt, 'ps_purchaseorderreceiptid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsPurchaseorderreceiptUpdate = Partial<Omit<PsPurchaseorderreceipt, 'ps_purchaseorderreceiptid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsPurchaseorderreceiptSelect = keyof PsPurchaseorderreceipt
export type PsPurchaseorderreceiptExpand = {
  ps_PurchaseOrderReceipt?: {
    select?: PsPurchaseorderreceiptlineSelect[]
    expand?: PsPurchaseorderreceiptlineExpand
  }
}


export const pspurchaseorderreceiptEntitySet: PsPurchaseorderreceiptEntitySet = 'ps_purchaseorderreceipts'
