/**
 * Auto-generated Dataverse Type
 * Generated on: 2026-01-21T03:03:52.359Z
 * Table: ps_relatedasset
 * 
 * This file is automatically generated. Do not edit manually.
 */

/**
 * Related Asset
 * Related Asset - Assets and equipment related to deliveries (e.g., vehicles, tools, equipment).
 */
export interface PsRelatedasset {
  // Primary Key
  ps_relatedassetid?: string

  // Business Fields
  ps_assetname?: string | null
  ps_name?: string | null
  ps_productname?: string | null

  // Choice Fields (Option Sets)
  /**
   * Choice Field (Option Set)
   */
    statecode?: number | null
  /**
   * Choice Field (Option Set)
   */
    statuscode?: number | null

  // Reference Fields (Lookups)
  ps_asset?: string | null
  ps_product?: string | null

  // Lookup Display Fields
  statecodename?: string | null
  statuscodename?: string | null

  // Audit Fields
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null

  // Ownership Fields
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null

  // System Fields
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null}

export type PsRelatedassetEntitySet = 'ps_relatedassets'

export type PsRelatedassetCreate = Omit<PsRelatedasset, 'ps_relatedassetid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsRelatedassetUpdate = Partial<Omit<PsRelatedasset, 'ps_relatedassetid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsRelatedassetSelect = keyof PsRelatedasset
export type PsRelatedassetExpand = Record<string, never>


export const psrelatedassetEntitySet: PsRelatedassetEntitySet = 'ps_relatedassets'
