/**
 * Auto-generated Dataverse Type
 * Generated on: 2026-01-21T03:03:52.359Z
 * Table: ps_setting
 * 
 * This file is automatically generated. Do not edit manually.
 */

import type { Account, AccountSelect, AccountExpand } from './Account.js'
import type { PsStaff, PsStaffSelect, PsStaffExpand } from './PsStaff.js'
import type { PsVehicledatabase, PsVehicledatabaseSelect, PsVehicledatabaseExpand } from './PsVehicledatabase.js'
import type { PsJoblist, PsJoblistSelect, PsJoblistExpand } from './PsJoblist.js'
import type { Product, ProductSelect, ProductExpand } from './Product.js'
import type { PsTerritorygroup, PsTerritorygroupSelect, PsTerritorygroupExpand } from './PsTerritorygroup.js'

/**
 * Setting
 * Application Settings - Configuration settings for the delivery and purchase order system.
 * 
 * RELATIONSHIPS:
 *   - ps_ClientStatus[]: Related Account records
 *   - ps_LeadStage[]: Related Account records
 *   - ps_Industry[]: Related Account records
 *   - ps_EmploymentStatus[]: Related PsStaff records
 *   - ps_Department[]: Related PsStaff records
 *   - ps_VehicleStatus[]: Vehicle assignments
 *   - ps_VehicleType[]: Vehicle assignments
 *   - ps_FuelType[]: Related PsVehicledatabase records
 *   - ps_OwnershipStatus[]: Related PsVehicledatabase records
 *   - ps_Location[]: Related PsVehicledatabase records
 *   - ps_JobStatus[]: Related PsJoblist records
 *   - ps_JobType[]: Related PsJoblist records
 *   - ps_Language[]: Related Account records
 *   - ps_PaymentTerms[]: Related Account records
 *   - ps_ProductCategory[]: Related products
 *   - ps_OrderTerritory[]: Related PsTerritorygroup records
 *   - ps_AccountClassification[]: Related Account records
 *   - ps_RelationshipType[]: Related Account records
 */
export interface PsSetting {
  // Primary Key
  ps_settingid?: string

  // Business Fields
  ps_apparea?: string | null
  ps_checkgroup?: string | null
  ps_checklisttype?: string | null
  ps_contact?: string | null
  ps_emergencycontacttype?: string | null
  ps_fillcolorvalue?: string | null
  ps_isarchivedname?: string
  ps_meetingtab?: unknown
  ps_meetingtabname?: string
  ps_name?: string | null
  ps_order?: number | null
  ps_relatedto?: string | null
  ps_settinggroup?: string | null
  ps_settingicon?: unknown
  ps_settingicon_timestamp?: number | null
  ps_settingicon_url?: string | null
  ps_settingtype?: string | null
  ps_textcolorvalue?: string | null

  // Choice Fields (Option Sets)
  /**
   * Choice Field (Option Set)
   */
    statecode?: number | null
  /**
   * Choice Field (Option Set)
   */
    statuscode?: number | null

  // Yes/No Fields (Two Options)
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    ps_isarchived?: boolean | null

  // Reference Fields (Lookups)
  ps_settingiconid?: string | null

  // Lookup Display Fields
  crd47_powerappiconname?: string | null
  statecodename?: string | null
  statuscodename?: string | null

  // Audit Fields
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null

  // Ownership Fields
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null

  // System Fields
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null

  // Other Fields
  new_url?: string | null

  // Relationships
  ps_ClientStatus?: Account[]
  ps_LeadStage?: Account[]
  ps_Industry?: Account[]
  ps_EmploymentStatus?: PsStaff[]
  ps_Department?: PsStaff[]
  ps_VehicleStatus?: PsVehicledatabase[]
  ps_VehicleType?: PsVehicledatabase[]
  ps_FuelType?: PsVehicledatabase[]
  ps_OwnershipStatus?: PsVehicledatabase[]
  ps_Location?: PsVehicledatabase[]
  ps_JobStatus?: PsJoblist[]
  ps_JobType?: PsJoblist[]
  ps_Language?: Account[]
  ps_PaymentTerms?: Account[]
  ps_ProductCategory?: Product[]
  ps_OrderTerritory?: PsTerritorygroup[]
  ps_AccountClassification?: Account[]
  ps_RelationshipType?: Account[]
}

export type PsSettingEntitySet = 'ps_settings'

export type PsSettingCreate = Omit<PsSetting, 'ps_settingid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsSettingUpdate = Partial<Omit<PsSetting, 'ps_settingid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsSettingSelect = keyof PsSetting
export type PsSettingExpand = {
  ps_ClientStatus?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  ps_LeadStage?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  ps_Industry?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  ps_EmploymentStatus?: {
    select?: PsStaffSelect[]
    expand?: PsStaffExpand
  }
  ps_Department?: {
    select?: PsStaffSelect[]
    expand?: PsStaffExpand
  }
  ps_VehicleStatus?: {
    select?: PsVehicledatabaseSelect[]
    expand?: PsVehicledatabaseExpand
  }
  ps_VehicleType?: {
    select?: PsVehicledatabaseSelect[]
    expand?: PsVehicledatabaseExpand
  }
  ps_FuelType?: {
    select?: PsVehicledatabaseSelect[]
    expand?: PsVehicledatabaseExpand
  }
  ps_OwnershipStatus?: {
    select?: PsVehicledatabaseSelect[]
    expand?: PsVehicledatabaseExpand
  }
  ps_Location?: {
    select?: PsVehicledatabaseSelect[]
    expand?: PsVehicledatabaseExpand
  }
  ps_JobStatus?: {
    select?: PsJoblistSelect[]
    expand?: PsJoblistExpand
  }
  ps_JobType?: {
    select?: PsJoblistSelect[]
    expand?: PsJoblistExpand
  }
  ps_Language?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  ps_PaymentTerms?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  ps_ProductCategory?: {
    select?: ProductSelect[]
    expand?: ProductExpand
  }
  ps_OrderTerritory?: {
    select?: PsTerritorygroupSelect[]
    expand?: PsTerritorygroupExpand
  }
  ps_AccountClassification?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  ps_RelationshipType?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
}


export const pssettingEntitySet: PsSettingEntitySet = 'ps_settings'
