/**
 * Auto-generated Dataverse Type
 * Generated on: 2026-01-21T03:03:52.361Z
 * Table: ps_staff
 * 
 * This file is automatically generated. Do not edit manually.
 */

import type { Account, AccountSelect, AccountExpand } from './Account.js'
import type { PsVehicledatabase, PsVehicledatabaseSelect, PsVehicledatabaseExpand } from './PsVehicledatabase.js'
import type { PsJoblist, PsJoblistSelect, PsJoblistExpand } from './PsJoblist.js'
import type { PsPurchaseorder, PsPurchaseorderSelect, PsPurchaseorderExpand } from './PsPurchaseorder.js'
import type { PsDeliveryschedule, PsDeliveryscheduleSelect, PsDeliveryscheduleExpand } from './PsDeliveryschedule.js'
import type { PsDeliveryroutes, PsDeliveryroutesSelect, PsDeliveryroutesExpand } from './PsDeliveryroutes.js'

/**
 * Staff
 * Staff - Employees including drivers, managers, and operations staff. Used to assign drivers (ps_driver) to delivery routes (PsDeliveryroutes) and managers to territories. Links to Azure AD users (Aaduser) for authentication.
 * 
 * RELATIONSHIPS:
 *   - crd47_AccountManager[]: Related Account records
 *   - ps_Staff[]: Staff/driver assignments
 *   - ps_AssignedOperator[]: Related PsVehicledatabase records
 *   - ps_OtherOperators[]: Related PsVehicledatabase records
 *   - ps_RelatedStaff[]: Staff/driver assignments
 *   - ps_Salesperson[]: Related PsJoblist records
 *   - ps_Manager[]: Related PsJoblist records
 *   - ps_Approver[]: Related PsPurchaseorder records
 *   - ps_StaffManager[]: Staff/driver assignments
 *   - ps_Operator[]: Related PsDeliveryschedule records
 *   - ps_driver[]: Staff/driver assignments
 *   - ps_deliveredby[]: Related PsDeliveryroutes records
 */
export interface PsStaff {
  // Primary Key
  ps_staffid?: string

  // Business Fields
  ps_departmentname?: string | null
  ps_employmentstatusname?: string | null
  ps_entraid?: string | null
  ps_entraname?: string | null
  ps_firstname?: string | null
  ps_isexistingname?: string
  ps_lastname?: string | null
  ps_managername?: string | null
  ps_microsoftlicence?: string | null
  ps_name?: string | null
  ps_onboardingstatusname?: string
  ps_personalemail?: string | null
  ps_photo?: unknown
  ps_photo_timestamp?: number | null
  ps_photo_url?: string | null
  ps_relatedstaffname?: string | null
  ps_rolename?: string | null
  ps_sharepointid?: number | null
  ps_staffmanagername?: string | null
  ps_staffnumber?: string | null
  ps_startdate?: string | null
  ps_username?: string | null
  ps_useryominame?: string | null

  // Choice Fields (Option Sets)
  /**
   * Choice Field (Option Set)
   * Options:
   * 125630000: Provision of Microsoft Account
   * 125630001: Allocation of Licence
   * 125630002: System Access Granted
   * 125630003: Onboarded
   */
    ps_onboardingstatus?: number | null
  /**
   * Choice Field (Option Set)
   */
    statecode?: number | null
  /**
   * Choice Field (Option Set)
   */
    statuscode?: number | null

  // Yes/No Fields (Two Options)
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    ps_isexisting?: boolean | null

  // Reference Fields (Lookups)
  ps_department?: string | null
  ps_employmentstatus?: string | null
  ps_entra?: string | null
  ps_manager?: string | null
  ps_photoid?: string | null
  ps_relatedstaff?: string | null
  ps_role?: string | null
  ps_staffmanager?: string | null
  ps_user?: string | null

  // Lookup Display Fields
  statecodename?: string | null
  statuscodename?: string | null

  // Audit Fields
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null

  // Ownership Fields
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null

  // System Fields
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null

  // Relationships
  crd47_AccountManager?: Account[]
  ps_Staff?: Account[]
  ps_AssignedOperator?: PsVehicledatabase[]
  ps_OtherOperators?: PsVehicledatabase[]
  ps_RelatedStaff?: PsStaff[]
  ps_Salesperson?: PsJoblist[]
  ps_Manager?: PsJoblist[]
  ps_Approver?: PsPurchaseorder[]
  ps_StaffManager?: PsStaff[]
  ps_Operator?: PsDeliveryschedule[]
  ps_driver?: PsDeliveryroutes[]
  ps_deliveredby?: PsDeliveryroutes[]
}

export type PsStaffEntitySet = 'ps_staffs'

export type PsStaffCreate = Omit<PsStaff, 'ps_staffid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsStaffUpdate = Partial<Omit<PsStaff, 'ps_staffid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsStaffSelect = keyof PsStaff
export type PsStaffExpand = {
  crd47_AccountManager?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  ps_Staff?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  ps_AssignedOperator?: {
    select?: PsVehicledatabaseSelect[]
    expand?: PsVehicledatabaseExpand
  }
  ps_OtherOperators?: {
    select?: PsVehicledatabaseSelect[]
    expand?: PsVehicledatabaseExpand
  }
  ps_RelatedStaff?: {
    select?: PsStaffSelect[]
    expand?: PsStaffExpand
  }
  ps_Salesperson?: {
    select?: PsJoblistSelect[]
    expand?: PsJoblistExpand
  }
  ps_Manager?: {
    select?: PsJoblistSelect[]
    expand?: PsJoblistExpand
  }
  ps_Approver?: {
    select?: PsPurchaseorderSelect[]
    expand?: PsPurchaseorderExpand
  }
  ps_StaffManager?: {
    select?: PsStaffSelect[]
    expand?: PsStaffExpand
  }
  ps_Operator?: {
    select?: PsDeliveryscheduleSelect[]
    expand?: PsDeliveryscheduleExpand
  }
  ps_driver?: {
    select?: PsDeliveryroutesSelect[]
    expand?: PsDeliveryroutesExpand
  }
  ps_deliveredby?: {
    select?: PsDeliveryroutesSelect[]
    expand?: PsDeliveryroutesExpand
  }
}


export const psstaffEntitySet: PsStaffEntitySet = 'ps_staffs'
