/**
 * Auto-generated Dataverse Type
 * Generated on: 2026-01-21T03:03:52.359Z
 * Table: ps_territorygroup
 * 
 * This file is automatically generated. Do not edit manually.
 */

import type { PsPostalareaboundary, PsPostalareaboundarySelect, PsPostalareaboundaryExpand } from './PsPostalareaboundary.js'
import type { PsDeliveryroutes, PsDeliveryroutesSelect, PsDeliveryroutesExpand } from './PsDeliveryroutes.js'
import type { PsDeliveryschedule, PsDeliveryscheduleSelect, PsDeliveryscheduleExpand } from './PsDeliveryschedule.js'

/**
 * Territory Group
 * Territory Group - Groups territories for organizing delivery routes by geographic regions.
 * 
 * RELATIONSHIPS:
 *   - ps_AssignedTerritoryGroup[]: Related PsPostalareaboundary records
 *   - ps_territorygroup[]: Related PsDeliveryroutes records
 *   - ps_TerritoryGroup[]: Related PsDeliveryschedule records
 */
export interface PsTerritorygroup {
  // Primary Key
  ps_territorygroupid?: string

  // Business Fields
  ps_color?: string | null
  ps_id?: string | null
  ps_name?: string | null
  ps_orderterritoryname?: string | null
  ps_territoryname?: string | null

  // Choice Fields (Option Sets)
  /**
   * Choice Field (Option Set)
   */
    statecode?: number | null
  /**
   * Choice Field (Option Set)
   */
    statuscode?: number | null

  // Reference Fields (Lookups)
  ps_orderterritory?: string | null
  ps_territory?: string | null

  // Lookup Display Fields
  statecodename?: string | null
  statuscodename?: string | null

  // Audit Fields
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null

  // Ownership Fields
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null

  // System Fields
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null

  // Relationships
  ps_AssignedTerritoryGroup?: PsPostalareaboundary[]
  ps_territorygroup?: PsDeliveryroutes[]
  ps_TerritoryGroup?: PsDeliveryschedule[]
}

export type PsTerritorygroupEntitySet = 'ps_territorygroups'

export type PsTerritorygroupCreate = Omit<PsTerritorygroup, 'ps_territorygroupid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsTerritorygroupUpdate = Partial<Omit<PsTerritorygroup, 'ps_territorygroupid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsTerritorygroupSelect = keyof PsTerritorygroup
export type PsTerritorygroupExpand = {
  ps_AssignedTerritoryGroup?: {
    select?: PsPostalareaboundarySelect[]
    expand?: PsPostalareaboundaryExpand
  }
  ps_territorygroup?: {
    select?: PsDeliveryroutesSelect[]
    expand?: PsDeliveryroutesExpand
  }
  ps_TerritoryGroup?: {
    select?: PsDeliveryscheduleSelect[]
    expand?: PsDeliveryscheduleExpand
  }
}


export const psterritorygroupEntitySet: PsTerritorygroupEntitySet = 'ps_territorygroups'
