/**
 * Auto-generated Dataverse Type
 * Generated on: 2026-01-21T03:03:52.360Z
 * Table: ps_vehicledatabase
 * 
 * This file is automatically generated. Do not edit manually.
 */

import type { PsDeliveryschedule, PsDeliveryscheduleSelect, PsDeliveryscheduleExpand } from './PsDeliveryschedule.js'
import type { PsRelatedasset, PsRelatedassetSelect, PsRelatedassetExpand } from './PsRelatedasset.js'
import type { PsJobassetattachment, PsJobassetattachmentSelect, PsJobassetattachmentExpand } from './PsJobassetattachment.js'
import type { PsDeliveryroutes, PsDeliveryroutesSelect, PsDeliveryroutesExpand } from './PsDeliveryroutes.js'

/**
 * Vehicle Database
 * Vehicle Database - Fleet management system tracking vehicles assigned to routes. Includes vehicle assignments to drivers (PsStaff) and capacity information for route planning.
 * 
 * RELATIONSHIPS:
 *   - ps_Vehicle[]: Vehicle assignments
 *   - ps_Asset[]: Related PsRelatedasset records
 *   - ps_Attachment[]: Related PsJobassetattachment records
 *   - ps_vehicle_route[]: Related PsDeliveryroutes records
 */
export interface PsVehicledatabase {
  // Primary Key
  ps_vehicledatabaseid?: string

  // Business Fields
  ps_assetmanagername?: string | null
  ps_assetmanageryominame?: string | null
  ps_assettypename?: string
  ps_assignedoperatorname?: string | null
  ps_barcode?: string | null
  ps_count?: number | null
  ps_currentvalue?: string | null
  ps_enginenumber?: string | null
  ps_fleetcardoffroad?: string | null
  ps_fleetcardonroad?: string | null
  ps_fueltypename?: string | null
  ps_hasissuename?: string
  ps_inspectionbookeddate?: string | null
  ps_inspectionbookedname?: string
  ps_inspectiondueby?: string | null
  ps_insurancecompany?: string | null
  ps_iscompanyownedname?: string
  ps_issuedetails?: string | null
  ps_issues?: string | null
  ps_lastservice?: string | null
  ps_locationname?: string | null
  ps_make?: string | null
  ps_model?: string | null
  ps_nextservice?: string | null
  ps_nickname?: string | null
  ps_notes?: string | null
  ps_otheroperatorsname?: string | null
  ps_ownershipstatusname?: string | null
  ps_plantid?: string | null
  ps_plate?: string | null
  ps_policynumber?: string | null
  ps_purchasedate?: string | null
  ps_purchaseprice?: string | null
  ps_registrationexpirationdate?: string | null
  ps_requireinspectionname?: string
  ps_scheduledforservicename?: string
  ps_searchvalue?: string | null
  ps_servicedueby?: string | null
  ps_serviceduebykm?: string | null
  ps_tolltag?: string | null
  ps_vehicleimage?: unknown
  ps_vehicleimage_timestamp?: number | null
  ps_vehicleimage_url?: string | null
  ps_vehiclestatusname?: string | null
  ps_vehicletypename?: string | null
  ps_vinnumber?: string | null
  ps_year?: number | null

  // Choice Fields (Option Sets)
  /**
   * Choice Field (Option Set)
   * Options:
   * 125630000: Vehicle
   * 125630001: General Asset
   */
    ps_assettype?: number | null
  /**
   * Choice Field (Option Set)
   */
    statecode?: number | null
  /**
   * Choice Field (Option Set)
   */
    statuscode?: number | null

  // Yes/No Fields (Two Options)
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    ps_hasissue?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    ps_inspectionbooked?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    ps_iscompanyowned?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    ps_requireinspection?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    ps_scheduledforservice?: boolean | null

  // Reference Fields (Lookups)
  ps_assetmanager?: string | null
  ps_assignedoperator?: string | null
  ps_fueltype?: string | null
  ps_location?: string | null
  ps_otheroperators?: string | null
  ps_ownershipstatus?: string | null
  ps_vehicleimageid?: string | null
  ps_vehiclestatus?: string | null
  ps_vehicletype?: string | null

  // Lookup Display Fields
  crd47_namename?: string | null
  statecodename?: string | null
  statuscodename?: string | null

  // Audit Fields
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null

  // Ownership Fields
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null

  // System Fields
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null

  // Other Fields
  crd47_name?: string | null

  // Relationships
  ps_Vehicle?: PsDeliveryschedule[]
  ps_Asset?: PsRelatedasset[]
  ps_Attachment?: PsJobassetattachment[]
  ps_vehicle_route?: PsDeliveryroutes[]
}

export type PsVehicledatabaseEntitySet = 'ps_vehicledatabases'

export type PsVehicledatabaseCreate = Omit<PsVehicledatabase, 'ps_vehicledatabaseid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsVehicledatabaseUpdate = Partial<Omit<PsVehicledatabase, 'ps_vehicledatabaseid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsVehicledatabaseSelect = keyof PsVehicledatabase
export type PsVehicledatabaseExpand = {
  ps_Vehicle?: {
    select?: PsDeliveryscheduleSelect[]
    expand?: PsDeliveryscheduleExpand
  }
  ps_Asset?: {
    select?: PsRelatedassetSelect[]
    expand?: PsRelatedassetExpand
  }
  ps_Attachment?: {
    select?: PsJobassetattachmentSelect[]
    expand?: PsJobassetattachmentExpand
  }
  ps_vehicle_route?: {
    select?: PsDeliveryroutesSelect[]
    expand?: PsDeliveryroutesExpand
  }
}


export const psvehicledatabaseEntitySet: PsVehicledatabaseEntitySet = 'ps_vehicledatabases'
