/**
 * Auto-generated Dataverse Type
 * Generated on: 2026-01-21T03:03:52.357Z
 * Table: salesorderdetail
 * 
 * This file is automatically generated. Do not edit manually.
 */

/**
 * Order Line
 * Line item in a sales order.
 * 
 * Sales Order Detail - Line items within a sales order, specifying products (Product) and quantities to be delivered. Each detail line links to a product and quantity.
 * 
 * RELATIONSHIPS:
 *   - parentbundleid_salesorderdetail[]: Related Salesorderdetail records
 *   - parentbundleidref_salesorderdetail[]: Related Salesorderdetail records
 */
export interface Salesorderdetail {
  // Primary Key
  salesorderdetailid?: string

  // Business Fields
  ps_friday?: number | null
  ps_monday?: number | null
  ps_ordersitepostalcode?: string | null
  ps_saturday?: number | null
  ps_sunday?: number | null
  ps_thursday?: number | null
  ps_totalweek?: number | null
  ps_tuesday?: number | null
  ps_wednesday?: number | null

  // Choice Fields (Option Sets)
  /**
   * Choice Field (Option Set)
   */
    msdyn_linetype?: number | null
  /**
   * Choice Field (Option Set)
   */
    ordercreationmethod?: number | null
  /**
   * Choice Field (Option Set)
   */
    pricingerrorcode?: number | null
  /**
   * Choice Field (Option Set)
   */
    producttypecode?: number | null
  /**
   * Choice Field (Option Set)
   */
    propertyconfigurationstatus?: number | null
  /**
   * Choice Field (Option Set)
   */
    salesorderstatecode?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: FOB
   * 2: No Charge
   */
    shipto_freighttermscode?: number | null
  /**
   * Choice Field (Option Set)
   */
    skippricecalculation?: number | null

  // Yes/No Fields (Two Options)
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    iscopied?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    ispriceoverridden?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    isproductoverridden?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    salesorderispricelocked?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    willcall?: boolean | null

  // Reference Fields (Lookups)
  msdyn_agreement?: string | null
  parentbundleid?: string | null
  parentbundleidref?: string | null
  productassociationid?: string | null
  productid?: string | null
  quotedetailid?: string | null
  salesorderid?: string | null
  salesrepid?: string | null
  shipto_addressid?: string | null
  transactioncurrencyid?: string | null
  uomid?: string | null

  // Lookup Display Fields
  iscopiedname?: string | null
  ispriceoverriddenname?: string | null
  isproductoverriddenname?: string | null
  msdyn_agreementname?: string | null
  msdyn_linetypename?: string | null
  ordercreationmethodname?: string | null
  pricingerrorcodename?: string | null
  productidname?: string | null
  productname?: string | null
  producttypecodename?: string | null
  propertyconfigurationstatusname?: string | null
  quotedetailidname?: string | null
  salesorderdetailname?: string | null
  salesorderidname?: string | null
  salesorderispricelockedname?: string | null
  salesorderstatecodename?: string | null
  salesrepidname?: string | null
  salesrepidyominame?: string | null
  shipto_contactname?: string | null
  shipto_freighttermscodename?: string | null
  shipto_name?: string | null
  skippricecalculationname?: string | null
  transactioncurrencyidname?: string | null
  uomidname?: string | null
  willcallname?: string | null

  // Audit Fields
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null

  // Ownership Fields
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningteam?: string | null
  owninguser?: string | null

  // System Fields
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null

  // Other Fields
  baseamount?: number | null
  baseamount_base?: number | null
  crd47_ordervalidfrom?: string | null
  crd47_ordervalidto?: string | null
  description?: string | null
  exchangerate?: number | null
  extendedamount?: number | null
  extendedamount_base?: number | null
  lineitemnumber?: number | null
  manualdiscountamount?: number | null
  manualdiscountamount_base?: number | null
  priceperunit?: number | null
  priceperunit_base?: number | null
  productdescription?: string | null
  productnumber?: string | null
  quantity?: number | null
  quantitybackordered?: number | null
  quantitycancelled?: number | null
  quantityshipped?: number | null
  requestdeliveryby?: string | null
  sequencenumber?: number | null
  shipto_city?: string | null
  shipto_country?: string | null
  shipto_fax?: string | null
  shipto_line1?: string | null
  shipto_line2?: string | null
  shipto_line3?: string | null
  shipto_postalcode?: string | null
  shipto_stateorprovince?: string | null
  shipto_telephone?: string | null
  tax?: number | null
  tax_base?: number | null
  volumediscountamount?: number | null
  volumediscountamount_base?: number | null

  // Relationships
  parentbundleid_salesorderdetail?: Salesorderdetail[]
  parentbundleidref_salesorderdetail?: Salesorderdetail[]
}

export type SalesorderdetailEntitySet = 'salesorderdetails'

export type SalesorderdetailCreate = Omit<Salesorderdetail, 'salesorderdetailid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type SalesorderdetailUpdate = Partial<Omit<Salesorderdetail, 'salesorderdetailid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type SalesorderdetailSelect = keyof Salesorderdetail
export type SalesorderdetailExpand = {
  parentbundleid_salesorderdetail?: {
    select?: SalesorderdetailSelect[]
    expand?: SalesorderdetailExpand
  }
  parentbundleidref_salesorderdetail?: {
    select?: SalesorderdetailSelect[]
    expand?: SalesorderdetailExpand
  }
}


export const salesorderdetailEntitySet: SalesorderdetailEntitySet = 'salesorderdetails'
