/**
 * Auto-generated Dataverse Type
 * Generated on: 2026-01-21T03:03:52.356Z
 * Table: salesorder
 * 
 * This file is automatically generated. Do not edit manually.
 */

import type { Salesorderdetail, SalesorderdetailSelect, SalesorderdetailExpand } from './Salesorderdetail.js'

/**
 * Order
 * Quote that has been accepted.
 * 
 * Sales Order - Customer orders that trigger delivery requirements. The sales order is the source document for creating delivery routes. When a customer places an order, it creates a sales order which then generates delivery route requirements.
 * 
 * RELATIONSHIPS:
 *   - orderdetails[]: Related Salesorderdetail records
 */
export interface Salesorder {
  // Primary Key
  salesorderid?: string

  // Business Fields
  ps_additionalinformation?: string | null
  ps_additionalnotes?: string | null
  ps_clientguid?: string | null
  ps_clientname?: string | null
  ps_clientyominame?: string | null
  ps_days?: unknown
  ps_daysname?: string
  ps_delivery_route_name?: string | null
  ps_deliveryinstruction?: string | null
  ps_deliveryroutename?: string | null
  ps_deliverystopsequence?: number | null
  ps_frequencyname?: string
  ps_keycontactname?: string | null
  ps_keycontactyominame?: string | null
  ps_ordersitename?: string | null
  ps_orderstatusname?: string
  ps_proofofdelivery?: unknown
  ps_proofofdelivery_timestamp?: number | null
  ps_proofofdelivery_url?: string | null
  ps_setvalidtodatename?: string
  ps_shiptolatitude?: number | null
  ps_shiptolongitude?: number | null
  ps_validfrom?: string | null
  ps_validto?: string | null
  ps_weeklyordername?: string | null

  // Choice Fields (Option Sets)
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: FOB
   * 2: No Charge
   */
    freighttermscode?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 192350000: Item based
   * 690970002: Service-Maintenance Based
   */
    msdyn_ordertype?: number | null
  /**
   * Choice Field (Option Set)
   */
    ordercreationmethod?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Net 30
   * 2: 2% 10, Net 30
   * 3: Net 45
   * 4: Net 60
   */
    paymenttermscode?: number | null
  /**
   * Choice Field (Option Set)
   */
    pricingerrorcode?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Default Value
   */
    prioritycode?: number | null
  /**
   * Choice Field (Option Set)
   */
    ps_frequency?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Draft
   * 125630001: Cancelled
   */
    ps_orderstatus?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Airborne
   * 2: DHL
   * 3: FedEx
   * 4: UPS
   * 5: Postal Mail
   * 6: Full Load
   * 7: Will Call
   */
    shippingmethodcode?: number | null
  /**
   * Choice Field (Option Set)
   * Options:
   * 1: Default Value
   */
    shipto_freighttermscode?: number | null
  /**
   * Choice Field (Option Set)
   */
    skippricecalculation?: number | null
  /**
   * Choice Field (Option Set)
   */
    statecode?: number | null
  /**
   * Choice Field (Option Set)
   */
    statuscode?: number | null

  // Yes/No Fields (Two Options)
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    ispricelocked?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    ps_setvalidtodate?: boolean | null
  /**
   * Yes/No Field (Two Options)
   * 1 = Yes
   * 0 = No
   */
    willcall?: boolean | null

  // Reference Fields (Lookups)
  accountid?: string | null
  billto_addressid?: string | null
  campaignid?: string | null
  contactid?: string | null
  customerid?: string | null
  entityimageid?: string | null
  msdyn_account?: string | null
  opportunityid?: string | null
  pricelevelid?: string | null
  processid?: string | null
  ps_client?: string | null
  ps_deliveryroute?: string | null
  ps_keycontact?: string | null
  ps_ordersite?: string | null
  ps_proofofdeliveryid?: string | null
  ps_weeklyorder?: string | null
  quoteid?: string | null
  shipto_addressid?: string | null
  slaid?: string | null
  slainvokedid?: string | null
  stageid?: string | null
  transactioncurrencyid?: string | null

  // Lookup Display Fields
  accountidname?: string | null
  accountidyominame?: string | null
  billto_contactname?: string | null
  billto_name?: string | null
  campaignidname?: string | null
  contactidname?: string | null
  contactidyominame?: string | null
  crd47_clientname?: string | null
  customeridname?: string | null
  customeridyominame?: string | null
  freighttermscodename?: string | null
  ispricelockedname?: string | null
  msdyn_accountname?: string | null
  msdyn_accountyominame?: string | null
  msdyn_ordertypename?: string | null
  name?: string | null
  opportunityidname?: string | null
  ordercreationmethodname?: string | null
  paymenttermscodename?: string | null
  pricelevelidname?: string | null
  pricingerrorcodename?: string | null
  prioritycodename?: string | null
  quoteidname?: string | null
  shippingmethodcodename?: string | null
  shipto_contactname?: string | null
  shipto_freighttermscodename?: string | null
  shipto_name?: string | null
  skippricecalculationname?: string | null
  slainvokedidname?: string | null
  slaname?: string | null
  statecodename?: string | null
  statuscodename?: string | null
  transactioncurrencyidname?: string | null
  willcallname?: string | null

  // Audit Fields
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null

  // Ownership Fields
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null

  // System Fields
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null

  // Other Fields
  billto_city?: string | null
  billto_composite?: string | null
  billto_country?: string | null
  billto_fax?: string | null
  billto_line1?: string | null
  billto_line2?: string | null
  billto_line3?: string | null
  billto_postalcode?: string | null
  billto_stateorprovince?: string | null
  billto_telephone?: string | null
  customeridtype?: string | null
  datefulfilled?: string | null
  description?: string | null
  discountamount?: number | null
  discountamount_base?: number | null
  discountpercentage?: number | null
  emailaddress?: string | null
  entityimage?: unknown
  entityimage_timestamp?: number | null
  entityimage_url?: string | null
  exchangerate?: number | null
  freightamount?: number | null
  freightamount_base?: number | null
  lastbackofficesubmit?: string | null
  lastonholdtime?: string | null
  msdyn_processstartedon?: string | null
  onholdtime?: number | null
  ordernumber?: string | null
  requestdeliveryby?: string | null
  shipto_city?: string | null
  shipto_composite?: string | null
  shipto_country?: string | null
  shipto_fax?: string | null
  shipto_line1?: string | null
  shipto_line2?: string | null
  shipto_line3?: string | null
  shipto_postalcode?: string | null
  shipto_stateorprovince?: string | null
  shipto_telephone?: string | null
  submitdate?: string | null
  submitstatus?: number | null
  submitstatusdescription?: string | null
  totalamount?: number | null
  totalamount_base?: number | null
  totalamountlessfreight?: number | null
  totalamountlessfreight_base?: number | null
  totaldiscountamount?: number | null
  totaldiscountamount_base?: number | null
  totallineitemamount?: number | null
  totallineitemamount_base?: number | null
  totallineitemdiscountamount?: number | null
  totallineitemdiscountamount_base?: number | null
  totaltax?: number | null
  totaltax_base?: number | null
  traversedpath?: string | null

  // Relationships
  orderdetails?: Salesorderdetail[]
}

export type SalesorderEntitySet = 'salesorders'

export type SalesorderCreate = Omit<Salesorder, 'salesorderid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type SalesorderUpdate = Partial<Omit<Salesorder, 'salesorderid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type SalesorderSelect = keyof Salesorder
export type SalesorderExpand = {
  orderdetails?: {
    select?: SalesorderdetailSelect[]
    expand?: SalesorderdetailExpand
  }
}


export const salesorderEntitySet: SalesorderEntitySet = 'salesorders'
