/**
 * Auto-generated Dataverse Types
 * Generated on: 2026-01-20T01:42:39.443Z
 * 
 * This file is automatically generated. Do not edit manually.
 */

/**
 * Delivery Routes
 * Table: ps_deliveryroutes
 */
export interface PsDeliveryroutes {
  ps_deliveryroutesid?: string
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null
  ps_sequence?: number | null
  ps_sitelat?: number | null
  ps_sitelong?: number | null
  ps_vehiclename?: string | null
  statecode?: number | null
  statecodename?: unknown
  statuscode?: number | null
  statuscodename?: unknown
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null
}

export type PsDeliveryroutesEntitySet = 'ps_deliveryrouteses'

export type PsDeliveryroutesCreate = Omit<PsDeliveryroutes, 'ps_deliveryroutesid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsDeliveryroutesUpdate = Partial<Omit<PsDeliveryroutes, 'ps_deliveryroutesid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsDeliveryroutesSelect = keyof PsDeliveryroutes
export type PsDeliveryroutesExpand = Record<string, never>

/**
 * Delivery Schedule
 * Table: ps_deliveryschedule
 */
export interface PsDeliveryschedule {
  ps_deliveryscheduleid?: string
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null
  ps_date?: string | null
  ps_id?: string | null
  ps_operator?: string | null
  ps_operatorname?: string | null
  ps_orderterritory?: string | null
  ps_orderterritoryname?: string | null
  ps_territorygroup?: string | null
  ps_territorygroupname?: string | null
  ps_territorytype?: number | null
  ps_territorytypename?: unknown
  ps_time?: string | null
  ps_vehicle?: string | null
  ps_vehiclename?: string | null
  statecode?: number | null
  statecodename?: unknown
  statuscode?: number | null
  statuscodename?: unknown
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null
}

export type PsDeliveryscheduleEntitySet = 'ps_deliveryschedules'

export type PsDeliveryscheduleCreate = Omit<PsDeliveryschedule, 'ps_deliveryscheduleid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsDeliveryscheduleUpdate = Partial<Omit<PsDeliveryschedule, 'ps_deliveryscheduleid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsDeliveryscheduleSelect = keyof PsDeliveryschedule
export type PsDeliveryscheduleExpand = Record<string, never>

/**
 * Job Asset Attachment
 * Table: ps_jobassetattachment
 */
export interface PsJobassetattachment {
  ps_jobassetattachmentid?: string
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null
  ps_assetnickname?: string | null
  ps_attachment?: string | null
  ps_attachmentid?: string | null
  ps_attachmentname?: string | null
  ps_id?: string | null
  ps_jobschedule?: string | null
  ps_jobscheduledate?: string | null
  ps_jobschedulename?: string | null
  statecode?: number | null
  statecodename?: unknown
  statuscode?: number | null
  statuscodename?: unknown
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null
}

export type PsJobassetattachmentEntitySet = 'ps_jobassetattachments'

export type PsJobassetattachmentCreate = Omit<PsJobassetattachment, 'ps_jobassetattachmentid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsJobassetattachmentUpdate = Partial<Omit<PsJobassetattachment, 'ps_jobassetattachmentid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsJobassetattachmentSelect = keyof PsJobassetattachment
export type PsJobassetattachmentExpand = Record<string, never>

/**
 * Order
 * Quote that has been accepted.
 */
export interface Salesorder {
  salesorderid?: string
  accountid?: string | null
  accountidname?: string | null
  accountidyominame?: string | null
  billto_addressid?: string | null
  billto_city?: string | null
  billto_composite?: string | null
  billto_contactname?: string | null
  billto_country?: string | null
  billto_fax?: string | null
  billto_line1?: string | null
  billto_line2?: string | null
  billto_line3?: string | null
  billto_name?: string | null
  billto_postalcode?: string | null
  billto_stateorprovince?: string | null
  billto_telephone?: string | null
  campaignid?: string | null
  campaignidname?: string | null
  contactid?: string | null
  contactidname?: string | null
  contactidyominame?: string | null
  crd47_clientname?: string | null
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  customerid?: string | null
  customeridname?: string | null
  customeridtype?: string | null
  customeridyominame?: string | null
  datefulfilled?: string | null
  description?: string | null
  discountamount?: number | null
  discountamount_base?: number | null
  discountpercentage?: number | null
  emailaddress?: string | null
  entityimage?: unknown
  entityimage_timestamp?: number | null
  entityimage_url?: string | null
  entityimageid?: string | null
  exchangerate?: number | null
  freightamount?: number | null
  freightamount_base?: number | null
  freighttermscode?: number | null
  freighttermscodename?: unknown
  importsequencenumber?: number | null
  ispricelocked?: boolean | null
  ispricelockedname?: unknown
  lastbackofficesubmit?: string | null
  lastonholdtime?: string | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  msdyn_account?: string | null
  msdyn_accountname?: string | null
  msdyn_accountyominame?: string | null
  msdyn_ordertype?: number | null
  msdyn_ordertypename?: unknown
  msdyn_processstartedon?: string | null
  name?: string | null
  onholdtime?: number | null
  opportunityid?: string | null
  opportunityidname?: string | null
  ordercreationmethod?: number | null
  ordercreationmethodname?: unknown
  ordernumber?: string | null
  overriddencreatedon?: string | null
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null
  paymenttermscode?: number | null
  paymenttermscodename?: unknown
  pricelevelid?: string | null
  pricelevelidname?: string | null
  pricingerrorcode?: number | null
  pricingerrorcodename?: unknown
  prioritycode?: number | null
  prioritycodename?: unknown
  processid?: string | null
  ps_additionalinformation?: string | null
  ps_additionalnotes?: string | null
  ps_client?: string | null
  ps_clientguid?: string | null
  ps_clientname?: string | null
  ps_clientyominame?: string | null
  ps_days?: unknown
  ps_daysname?: unknown
  ps_deliveryinstruction?: string | null
  ps_frequency?: number | null
  ps_frequencyname?: unknown
  ps_keycontact?: string | null
  ps_keycontactname?: string | null
  ps_keycontactyominame?: string | null
  ps_ordersite?: string | null
  ps_ordersitename?: string | null
  ps_orderstatus?: number | null
  ps_orderstatusname?: unknown
  ps_proofofdelivery?: unknown
  ps_proofofdelivery_timestamp?: number | null
  ps_proofofdelivery_url?: string | null
  ps_proofofdeliveryid?: string | null
  ps_setvalidtodate?: boolean | null
  ps_setvalidtodatename?: unknown
  ps_shiptolatitude?: number | null
  ps_shiptolongitude?: number | null
  ps_validfrom?: string | null
  ps_validto?: string | null
  ps_weeklyorder?: string | null
  ps_weeklyordername?: string | null
  quoteid?: string | null
  quoteidname?: string | null
  requestdeliveryby?: string | null
  shippingmethodcode?: number | null
  shippingmethodcodename?: unknown
  shipto_addressid?: string | null
  shipto_city?: string | null
  shipto_composite?: string | null
  shipto_contactname?: string | null
  shipto_country?: string | null
  shipto_fax?: string | null
  shipto_freighttermscode?: number | null
  shipto_freighttermscodename?: unknown
  shipto_line1?: string | null
  shipto_line2?: string | null
  shipto_line3?: string | null
  shipto_name?: string | null
  shipto_postalcode?: string | null
  shipto_stateorprovince?: string | null
  shipto_telephone?: string | null
  skippricecalculation?: number | null
  skippricecalculationname?: unknown
  slaid?: string | null
  slainvokedid?: string | null
  slainvokedidname?: string | null
  slaname?: string | null
  stageid?: string | null
  statecode?: number | null
  statecodename?: unknown
  statuscode?: number | null
  statuscodename?: unknown
  submitdate?: string | null
  submitstatus?: number | null
  submitstatusdescription?: string | null
  timezoneruleversionnumber?: number | null
  totalamount?: number | null
  totalamount_base?: number | null
  totalamountlessfreight?: number | null
  totalamountlessfreight_base?: number | null
  totaldiscountamount?: number | null
  totaldiscountamount_base?: number | null
  totallineitemamount?: number | null
  totallineitemamount_base?: number | null
  totallineitemdiscountamount?: number | null
  totallineitemdiscountamount_base?: number | null
  totaltax?: number | null
  totaltax_base?: number | null
  transactioncurrencyid?: string | null
  transactioncurrencyidname?: string | null
  traversedpath?: string | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null
  willcall?: boolean | null
  willcallname?: unknown


  // Relationships
  orderdetails?: Salesorderdetail[]
}

export type SalesorderEntitySet = 'salesorders'

export type SalesorderCreate = Omit<Salesorder, 'salesorderid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type SalesorderUpdate = Partial<Omit<Salesorder, 'salesorderid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type SalesorderSelect = keyof Salesorder
export type SalesorderExpand = {
  orderdetails?: {
    select?: SalesorderdetailSelect[]
    expand?: SalesorderdetailExpand
  }
}

/**
 * Order Line
 * Line item in a sales order.
 */
export interface Salesorderdetail {
  salesorderdetailid?: string
  baseamount?: number | null
  baseamount_base?: number | null
  crd47_ordervalidfrom?: string | null
  crd47_ordervalidto?: string | null
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  description?: string | null
  exchangerate?: number | null
  extendedamount?: number | null
  extendedamount_base?: number | null
  importsequencenumber?: number | null
  iscopied?: boolean | null
  iscopiedname?: unknown
  ispriceoverridden?: boolean | null
  ispriceoverriddenname?: unknown
  isproductoverridden?: boolean | null
  isproductoverriddenname?: unknown
  lineitemnumber?: number | null
  manualdiscountamount?: number | null
  manualdiscountamount_base?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  msdyn_agreement?: string | null
  msdyn_agreementname?: string | null
  msdyn_linetype?: number | null
  msdyn_linetypename?: unknown
  ordercreationmethod?: number | null
  ordercreationmethodname?: unknown
  overriddencreatedon?: string | null
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningteam?: string | null
  owninguser?: string | null
  parentbundleid?: string | null
  parentbundleidref?: string | null
  priceperunit?: number | null
  priceperunit_base?: number | null
  pricingerrorcode?: number | null
  pricingerrorcodename?: unknown
  productassociationid?: string | null
  productdescription?: string | null
  productid?: string | null
  productidname?: string | null
  productname?: string | null
  productnumber?: string | null
  producttypecode?: number | null
  producttypecodename?: unknown
  propertyconfigurationstatus?: number | null
  propertyconfigurationstatusname?: unknown
  ps_friday?: number | null
  ps_monday?: number | null
  ps_ordersitepostalcode?: string | null
  ps_saturday?: number | null
  ps_sunday?: number | null
  ps_thursday?: number | null
  ps_totalweek?: number | null
  ps_tuesday?: number | null
  ps_wednesday?: number | null
  quantity?: number | null
  quantitybackordered?: number | null
  quantitycancelled?: number | null
  quantityshipped?: number | null
  quotedetailid?: string | null
  quotedetailidname?: string | null
  requestdeliveryby?: string | null
  salesorderdetailname?: string | null
  salesorderid?: string | null
  salesorderidname?: string | null
  salesorderispricelocked?: boolean | null
  salesorderispricelockedname?: unknown
  salesorderstatecode?: number | null
  salesorderstatecodename?: unknown
  salesrepid?: string | null
  salesrepidname?: string | null
  salesrepidyominame?: string | null
  sequencenumber?: number | null
  shipto_addressid?: string | null
  shipto_city?: string | null
  shipto_contactname?: string | null
  shipto_country?: string | null
  shipto_fax?: string | null
  shipto_freighttermscode?: number | null
  shipto_freighttermscodename?: unknown
  shipto_line1?: string | null
  shipto_line2?: string | null
  shipto_line3?: string | null
  shipto_name?: string | null
  shipto_postalcode?: string | null
  shipto_stateorprovince?: string | null
  shipto_telephone?: string | null
  skippricecalculation?: number | null
  skippricecalculationname?: unknown
  tax?: number | null
  tax_base?: number | null
  timezoneruleversionnumber?: number | null
  transactioncurrencyid?: string | null
  transactioncurrencyidname?: string | null
  uomid?: string | null
  uomidname?: string | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null
  volumediscountamount?: number | null
  volumediscountamount_base?: number | null
  willcall?: boolean | null
  willcallname?: unknown


  // Relationships
  parentbundleid_salesorderdetail?: Salesorderdetail[]
  parentbundleidref_salesorderdetail?: Salesorderdetail[]
}

export type SalesorderdetailEntitySet = 'salesorderdetails'

export type SalesorderdetailCreate = Omit<Salesorderdetail, 'salesorderdetailid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type SalesorderdetailUpdate = Partial<Omit<Salesorderdetail, 'salesorderdetailid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type SalesorderdetailSelect = keyof Salesorderdetail
export type SalesorderdetailExpand = {
  parentbundleid_salesorderdetail?: {
    select?: SalesorderdetailSelect[]
    expand?: SalesorderdetailExpand
  }
  parentbundleidref_salesorderdetail?: {
    select?: SalesorderdetailSelect[]
    expand?: SalesorderdetailExpand
  }
}

/**
 * Postal Area Boundary
 * Table: ps_postalareaboundary
 */
export interface PsPostalareaboundary {
  ps_postalareaboundaryid?: string
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null
  ps_assignedterritorygroup?: string | null
  ps_assignedterritorygroupname?: string | null
  ps_color?: string | null
  ps_geojson?: string | null
  ps_id?: string | null
  ps_latitude?: number | null
  ps_longitude?: number | null
  ps_postcode?: string | null
  ps_territorygroupcolor?: string | null
  statecode?: number | null
  statecodename?: unknown
  statuscode?: number | null
  statuscodename?: unknown
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null
}

export type PsPostalareaboundaryEntitySet = 'ps_postalareaboundaries'

export type PsPostalareaboundaryCreate = Omit<PsPostalareaboundary, 'ps_postalareaboundaryid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsPostalareaboundaryUpdate = Partial<Omit<PsPostalareaboundary, 'ps_postalareaboundaryid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsPostalareaboundarySelect = keyof PsPostalareaboundary
export type PsPostalareaboundaryExpand = Record<string, never>

/**
 * Related Asset
 * Table: ps_relatedasset
 */
export interface PsRelatedasset {
  ps_relatedassetid?: string
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null
  ps_asset?: string | null
  ps_assetname?: string | null
  ps_name?: string | null
  ps_product?: string | null
  ps_productname?: string | null
  statecode?: number | null
  statecodename?: unknown
  statuscode?: number | null
  statuscodename?: unknown
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null
}

export type PsRelatedassetEntitySet = 'ps_relatedassets'

export type PsRelatedassetCreate = Omit<PsRelatedasset, 'ps_relatedassetid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsRelatedassetUpdate = Partial<Omit<PsRelatedasset, 'ps_relatedassetid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsRelatedassetSelect = keyof PsRelatedasset
export type PsRelatedassetExpand = Record<string, never>

/**
 * Setting
 * Table: ps_setting
 */
export interface PsSetting {
  ps_settingid?: string
  crd47_powerappiconname?: string | null
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  new_url?: string | null
  overriddencreatedon?: string | null
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null
  ps_apparea?: string | null
  ps_checkgroup?: string | null
  ps_checklisttype?: string | null
  ps_contact?: string | null
  ps_emergencycontacttype?: string | null
  ps_fillcolorvalue?: string | null
  ps_isarchived?: boolean | null
  ps_isarchivedname?: unknown
  ps_meetingtab?: unknown
  ps_meetingtabname?: unknown
  ps_name?: string | null
  ps_order?: number | null
  ps_relatedto?: string | null
  ps_settinggroup?: string | null
  ps_settingicon?: unknown
  ps_settingicon_timestamp?: number | null
  ps_settingicon_url?: string | null
  ps_settingiconid?: string | null
  ps_settingtype?: string | null
  ps_textcolorvalue?: string | null
  statecode?: number | null
  statecodename?: unknown
  statuscode?: number | null
  statuscodename?: unknown
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null


  // Relationships
  ps_ClientStatus?: Account[]
  ps_LeadStage?: Account[]
  ps_Industry?: Account[]
  ps_EmploymentStatus?: PsStaff[]
  ps_Department?: PsStaff[]
  ps_VehicleStatus?: PsVehicledatabase[]
  ps_VehicleType?: PsVehicledatabase[]
  ps_FuelType?: PsVehicledatabase[]
  ps_OwnershipStatus?: PsVehicledatabase[]
  ps_Location?: PsVehicledatabase[]
  ps_Language?: Account[]
  ps_PaymentTerms?: Account[]
  ps_ProductCategory?: Product[]
  ps_OrderTerritory?: PsTerritorygroup[]
  ps_AccountClassification?: Account[]
  ps_RelationshipType?: Account[]
}

export type PsSettingEntitySet = 'ps_settings'

export type PsSettingCreate = Omit<PsSetting, 'ps_settingid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsSettingUpdate = Partial<Omit<PsSetting, 'ps_settingid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsSettingSelect = keyof PsSetting
export type PsSettingExpand = {
  ps_ClientStatus?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  ps_LeadStage?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  ps_Industry?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  ps_EmploymentStatus?: {
    select?: PsStaffSelect[]
    expand?: PsStaffExpand
  }
  ps_Department?: {
    select?: PsStaffSelect[]
    expand?: PsStaffExpand
  }
  ps_VehicleStatus?: {
    select?: PsVehicledatabaseSelect[]
    expand?: PsVehicledatabaseExpand
  }
  ps_VehicleType?: {
    select?: PsVehicledatabaseSelect[]
    expand?: PsVehicledatabaseExpand
  }
  ps_FuelType?: {
    select?: PsVehicledatabaseSelect[]
    expand?: PsVehicledatabaseExpand
  }
  ps_OwnershipStatus?: {
    select?: PsVehicledatabaseSelect[]
    expand?: PsVehicledatabaseExpand
  }
  ps_Location?: {
    select?: PsVehicledatabaseSelect[]
    expand?: PsVehicledatabaseExpand
  }
  ps_Language?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  ps_PaymentTerms?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  ps_ProductCategory?: {
    select?: ProductSelect[]
    expand?: ProductExpand
  }
  ps_OrderTerritory?: {
    select?: PsTerritorygroupSelect[]
    expand?: PsTerritorygroupExpand
  }
  ps_AccountClassification?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  ps_RelationshipType?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
}

/**
 * Territory Group
 * Table: ps_territorygroup
 */
export interface PsTerritorygroup {
  ps_territorygroupid?: string
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null
  ps_color?: string | null
  ps_id?: string | null
  ps_name?: string | null
  ps_orderterritory?: string | null
  ps_orderterritoryname?: string | null
  ps_territory?: string | null
  ps_territoryname?: string | null
  statecode?: number | null
  statecodename?: unknown
  statuscode?: number | null
  statuscodename?: unknown
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null


  // Relationships
  ps_AssignedTerritoryGroup?: PsPostalareaboundary[]
  ps_TerritoryGroup?: PsDeliveryschedule[]
}

export type PsTerritorygroupEntitySet = 'ps_territorygroups'

export type PsTerritorygroupCreate = Omit<PsTerritorygroup, 'ps_territorygroupid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsTerritorygroupUpdate = Partial<Omit<PsTerritorygroup, 'ps_territorygroupid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsTerritorygroupSelect = keyof PsTerritorygroup
export type PsTerritorygroupExpand = {
  ps_AssignedTerritoryGroup?: {
    select?: PsPostalareaboundarySelect[]
    expand?: PsPostalareaboundaryExpand
  }
  ps_TerritoryGroup?: {
    select?: PsDeliveryscheduleSelect[]
    expand?: PsDeliveryscheduleExpand
  }
}

/**
 * Vehicle Database
 * Table: ps_vehicledatabase
 */
export interface PsVehicledatabase {
  ps_vehicledatabaseid?: string
  crd47_name?: string | null
  crd47_namename?: string | null
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null
  ps_assetmanager?: string | null
  ps_assetmanagername?: string | null
  ps_assetmanageryominame?: string | null
  ps_assettype?: number | null
  ps_assettypename?: unknown
  ps_assignedoperator?: string | null
  ps_assignedoperatorname?: string | null
  ps_barcode?: string | null
  ps_count?: number | null
  ps_currentvalue?: string | null
  ps_enginenumber?: string | null
  ps_fleetcardoffroad?: string | null
  ps_fleetcardonroad?: string | null
  ps_fueltype?: string | null
  ps_fueltypename?: string | null
  ps_hasissue?: boolean | null
  ps_hasissuename?: unknown
  ps_inspectionbooked?: boolean | null
  ps_inspectionbookeddate?: string | null
  ps_inspectionbookedname?: unknown
  ps_inspectiondueby?: string | null
  ps_insurancecompany?: string | null
  ps_iscompanyowned?: boolean | null
  ps_iscompanyownedname?: unknown
  ps_issuedetails?: string | null
  ps_issues?: string | null
  ps_lastservice?: string | null
  ps_location?: string | null
  ps_locationname?: string | null
  ps_make?: string | null
  ps_model?: string | null
  ps_nextservice?: string | null
  ps_nickname?: string | null
  ps_notes?: string | null
  ps_otheroperators?: string | null
  ps_otheroperatorsname?: string | null
  ps_ownershipstatus?: string | null
  ps_ownershipstatusname?: string | null
  ps_plantid?: string | null
  ps_plate?: string | null
  ps_policynumber?: string | null
  ps_purchasedate?: string | null
  ps_purchaseprice?: string | null
  ps_registrationexpirationdate?: string | null
  ps_requireinspection?: boolean | null
  ps_requireinspectionname?: unknown
  ps_scheduledforservice?: boolean | null
  ps_scheduledforservicename?: unknown
  ps_searchvalue?: string | null
  ps_servicedueby?: string | null
  ps_serviceduebykm?: string | null
  ps_tolltag?: string | null
  ps_vehicleimage?: unknown
  ps_vehicleimage_timestamp?: number | null
  ps_vehicleimage_url?: string | null
  ps_vehicleimageid?: string | null
  ps_vehiclestatus?: string | null
  ps_vehiclestatusname?: string | null
  ps_vehicletype?: string | null
  ps_vehicletypename?: string | null
  ps_vinnumber?: string | null
  ps_year?: number | null
  statecode?: number | null
  statecodename?: unknown
  statuscode?: number | null
  statuscodename?: unknown
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null


  // Relationships
  ps_Vehicle?: PsDeliveryschedule[]
  ps_Asset?: PsRelatedasset[]
  ps_Attachment?: PsJobassetattachment[]
}

export type PsVehicledatabaseEntitySet = 'ps_vehicledatabases'

export type PsVehicledatabaseCreate = Omit<PsVehicledatabase, 'ps_vehicledatabaseid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsVehicledatabaseUpdate = Partial<Omit<PsVehicledatabase, 'ps_vehicledatabaseid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsVehicledatabaseSelect = keyof PsVehicledatabase
export type PsVehicledatabaseExpand = {
  ps_Vehicle?: {
    select?: PsDeliveryscheduleSelect[]
    expand?: PsDeliveryscheduleExpand
  }
  ps_Asset?: {
    select?: PsRelatedassetSelect[]
    expand?: PsRelatedassetExpand
  }
  ps_Attachment?: {
    select?: PsJobassetattachmentSelect[]
    expand?: PsJobassetattachmentExpand
  }
}

/**
 * Staff
 * Table: ps_staff
 */
export interface PsStaff {
  ps_staffid?: string
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null
  ps_department?: string | null
  ps_departmentname?: string | null
  ps_employmentstatus?: string | null
  ps_employmentstatusname?: string | null
  ps_entra?: string | null
  ps_entraid?: string | null
  ps_entraname?: string | null
  ps_firstname?: string | null
  ps_isexisting?: boolean | null
  ps_isexistingname?: unknown
  ps_lastname?: string | null
  ps_manager?: string | null
  ps_managername?: string | null
  ps_microsoftlicence?: string | null
  ps_name?: string | null
  ps_onboardingstatus?: number | null
  ps_onboardingstatusname?: unknown
  ps_personalemail?: string | null
  ps_photo?: unknown
  ps_photo_timestamp?: number | null
  ps_photo_url?: string | null
  ps_photoid?: string | null
  ps_relatedstaff?: string | null
  ps_relatedstaffname?: string | null
  ps_role?: string | null
  ps_rolename?: string | null
  ps_sharepointid?: number | null
  ps_staffmanager?: string | null
  ps_staffmanagername?: string | null
  ps_staffnumber?: string | null
  ps_startdate?: string | null
  ps_user?: string | null
  ps_username?: string | null
  ps_useryominame?: string | null
  statecode?: number | null
  statecodename?: unknown
  statuscode?: number | null
  statuscodename?: unknown
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null


  // Relationships
  crd47_AccountManager?: Account[]
  ps_Staff?: Account[]
  ps_AssignedOperator?: PsVehicledatabase[]
  ps_OtherOperators?: PsVehicledatabase[]
  ps_RelatedStaff?: PsStaff[]
  ps_StaffManager?: PsStaff[]
  ps_Operator?: PsDeliveryschedule[]
}

export type PsStaffEntitySet = 'ps_staffs'

export type PsStaffCreate = Omit<PsStaff, 'ps_staffid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsStaffUpdate = Partial<Omit<PsStaff, 'ps_staffid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsStaffSelect = keyof PsStaff
export type PsStaffExpand = {
  crd47_AccountManager?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  ps_Staff?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  ps_AssignedOperator?: {
    select?: PsVehicledatabaseSelect[]
    expand?: PsVehicledatabaseExpand
  }
  ps_OtherOperators?: {
    select?: PsVehicledatabaseSelect[]
    expand?: PsVehicledatabaseExpand
  }
  ps_RelatedStaff?: {
    select?: PsStaffSelect[]
    expand?: PsStaffExpand
  }
  ps_StaffManager?: {
    select?: PsStaffSelect[]
    expand?: PsStaffExpand
  }
  ps_Operator?: {
    select?: PsDeliveryscheduleSelect[]
    expand?: PsDeliveryscheduleExpand
  }
}

/**
 * Product
 * Information about products and their pricing information.
 */
export interface Product {
  productid?: string
  crd47_entity?: number | null
  crd47_entityname?: unknown
  crd47_hasminimumcharge?: boolean | null
  crd47_hasminimumchargeamount?: number | null
  crd47_hasminimumchargename?: unknown
  crd47_minimumchargetype?: number | null
  crd47_minimumchargetypename?: unknown
  createdby?: string | null
  createdbyexternalparty?: string | null
  createdbyexternalpartyname?: string | null
  createdbyexternalpartyyominame?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  currentcost?: number | null
  currentcost_base?: number | null
  defaultuomid?: string | null
  defaultuomidname?: string | null
  defaultuomscheduleid?: string | null
  defaultuomscheduleidname?: string | null
  description?: string | null
  dmtimportstate?: number | null
  entityimage?: unknown
  entityimage_timestamp?: number | null
  entityimage_url?: string | null
  entityimageid?: string | null
  exchangerate?: number | null
  hierarchypath?: string | null
  importsequencenumber?: number | null
  iskit?: boolean | null
  iskitname?: unknown
  isreparented?: boolean | null
  isreparentedname?: unknown
  isstockitem?: boolean | null
  isstockitemname?: unknown
  modifiedby?: string | null
  modifiedbyexternalparty?: string | null
  modifiedbyexternalpartyname?: string | null
  modifiedbyexternalpartyyominame?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  msdyn_alsoknownas?: string | null
  msdyn_converttocustomerasset?: boolean | null
  msdyn_converttocustomerassetname?: unknown
  msdyn_defaultvendor?: string | null
  msdyn_defaultvendorname?: string | null
  msdyn_defaultvendoryominame?: string | null
  msdyn_fieldserviceproducttype?: number | null
  msdyn_fieldserviceproducttypename?: unknown
  msdyn_gdproptout?: boolean | null
  msdyn_gdproptoutname?: unknown
  msdyn_purchasename?: string | null
  msdyn_scopes?: string | null
  msdyn_taxable?: boolean | null
  msdyn_taxablename?: unknown
  msdyn_upccode?: string | null
  name?: string | null
  organizationid?: string | null
  organizationidname?: string | null
  overriddencreatedon?: string | null
  parentproductid?: string | null
  parentproductidname?: string | null
  price?: number | null
  price_base?: number | null
  pricelevelid?: string | null
  pricelevelidname?: string | null
  processid?: string | null
  productnumber?: string | null
  productstructure?: number | null
  productstructurename?: unknown
  producttypecode?: number | null
  producttypecodename?: unknown
  producturl?: string | null
  ps_characteristics?: string | null
  ps_characteristicsname?: string | null
  ps_form?: string | null
  ps_formasset?: boolean | null
  ps_formassetname?: unknown
  ps_formname?: string | null
  ps_inventorycategory?: number | null
  ps_inventorycategoryname?: unknown
  ps_linenumber?: string | null
  ps_metric?: string | null
  ps_metricname?: string | null
  ps_minimumquantity?: number | null
  ps_productcategory?: string | null
  ps_productcategoryname?: string | null
  ps_purchaseorderline?: string | null
  ps_purchaseorderlinename?: string | null
  ps_rackstandard?: number | null
  ps_remainingquantity?: number | null
  ps_sourcetype?: number | null
  ps_sourcetypename?: unknown
  ps_supplier?: string | null
  ps_suppliername?: string | null
  ps_supplieryominame?: string | null
  ps_trolleystandard?: number | null
  ps_trolleytall?: number | null
  quantitydecimal?: number | null
  quantityonhand?: number | null
  size?: string | null
  stageid?: string | null
  standardcost?: number | null
  standardcost_base?: number | null
  statecode?: number | null
  statecodename?: unknown
  statuscode?: number | null
  statuscodename?: unknown
  stockvolume?: number | null
  stockweight?: number | null
  subjectid?: string | null
  subjectidname?: string | null
  suppliername?: string | null
  timezoneruleversionnumber?: number | null
  transactioncurrencyid?: string | null
  transactioncurrencyidname?: string | null
  traversedpath?: string | null
  utcconversiontimezonecode?: number | null
  validfromdate?: string | null
  validtodate?: string | null
  vendorid?: string | null
  vendorname?: string | null
  vendorpartnumber?: string | null
  versionnumber?: number | null


  // Relationships
  productparentproduct?: Product[]
  productorderdetails?: Salesorderdetail[]
  crd47_Name?: PsVehicledatabase[]
  ps_Product?: PsRelatedasset[]
}

export type ProductEntitySet = 'products'

export type ProductCreate = Omit<Product, 'productid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby'>
export type ProductUpdate = Partial<Omit<Product, 'productid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type ProductSelect = keyof Product
export type ProductExpand = {
  productparentproduct?: {
    select?: ProductSelect[]
    expand?: ProductExpand
  }
  productorderdetails?: {
    select?: SalesorderdetailSelect[]
    expand?: SalesorderdetailExpand
  }
  crd47_Name?: {
    select?: PsVehicledatabaseSelect[]
    expand?: PsVehicledatabaseExpand
  }
  ps_Product?: {
    select?: PsRelatedassetSelect[]
    expand?: PsRelatedassetExpand
  }
}

/**
 * Account
 * Business that represents a customer or potential customer. The company that is billed in business transactions.
 */
export interface Account {
  accountid?: string
  accountcategorycode?: number | null
  accountcategorycodename?: unknown
  accountclassificationcode?: number | null
  accountclassificationcodename?: unknown
  accountnumber?: string | null
  accountratingcode?: number | null
  accountratingcodename?: unknown
  address1_addressid?: string | null
  address1_addresstypecode?: number | null
  address1_addresstypecodename?: unknown
  address1_city?: string | null
  address1_composite?: string | null
  address1_country?: string | null
  address1_county?: string | null
  address1_fax?: string | null
  address1_freighttermscode?: number | null
  address1_freighttermscodename?: unknown
  address1_latitude?: number | null
  address1_line1?: string | null
  address1_line2?: string | null
  address1_line3?: string | null
  address1_longitude?: number | null
  address1_name?: string | null
  address1_postalcode?: string | null
  address1_postofficebox?: string | null
  address1_primarycontactname?: string | null
  address1_shippingmethodcode?: number | null
  address1_shippingmethodcodename?: unknown
  address1_stateorprovince?: string | null
  address1_telephone1?: string | null
  address1_telephone2?: string | null
  address1_telephone3?: string | null
  address1_upszone?: string | null
  address1_utcoffset?: number | null
  address2_addressid?: string | null
  address2_addresstypecode?: number | null
  address2_addresstypecodename?: unknown
  address2_city?: string | null
  address2_composite?: string | null
  address2_country?: string | null
  address2_county?: string | null
  address2_fax?: string | null
  address2_freighttermscode?: number | null
  address2_freighttermscodename?: unknown
  address2_latitude?: number | null
  address2_line1?: string | null
  address2_line2?: string | null
  address2_line3?: string | null
  address2_longitude?: number | null
  address2_name?: string | null
  address2_postalcode?: string | null
  address2_postofficebox?: string | null
  address2_primarycontactname?: string | null
  address2_shippingmethodcode?: number | null
  address2_shippingmethodcodename?: unknown
  address2_stateorprovince?: string | null
  address2_telephone1?: string | null
  address2_telephone2?: string | null
  address2_telephone3?: string | null
  address2_upszone?: string | null
  address2_utcoffset?: number | null
  adx_createdbyipaddress?: string | null
  adx_createdbyusername?: string | null
  adx_modifiedbyipaddress?: string | null
  adx_modifiedbyusername?: string | null
  aging30?: number | null
  aging30_base?: number | null
  aging60?: number | null
  aging60_base?: number | null
  aging90?: number | null
  aging90_base?: number | null
  businesstypecode?: number | null
  businesstypecodename?: unknown
  crd47_abn?: string | null
  crd47_accountmanager?: string | null
  crd47_accountmanagername?: string | null
  crd47_engagementdate?: string | null
  crd47_sharepointid?: number | null
  crd47_sharepointname?: string | null
  crd47_shortname?: string | null
  createdby?: string | null
  createdbyexternalparty?: string | null
  createdbyexternalpartyname?: string | null
  createdbyexternalpartyyominame?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  creditlimit?: number | null
  creditlimit_base?: number | null
  creditonhold?: boolean | null
  creditonholdname?: unknown
  customersizecode?: number | null
  customersizecodename?: unknown
  customertypecode?: number | null
  customertypecodename?: unknown
  defaultpricelevelid?: string | null
  defaultpricelevelidname?: string | null
  description?: string | null
  donotbulkemail?: boolean | null
  donotbulkemailname?: unknown
  donotbulkpostalmail?: boolean | null
  donotbulkpostalmailname?: unknown
  donotemail?: boolean | null
  donotemailname?: unknown
  donotfax?: boolean | null
  donotfaxname?: unknown
  donotphone?: boolean | null
  donotphonename?: unknown
  donotpostalmail?: boolean | null
  donotpostalmailname?: unknown
  donotsendmarketingmaterialname?: unknown
  donotsendmm?: boolean | null
  emailaddress1?: string | null
  emailaddress2?: string | null
  emailaddress3?: string | null
  entityimage?: unknown
  entityimage_timestamp?: number | null
  entityimage_url?: string | null
  entityimageid?: string | null
  exchangerate?: number | null
  fax?: string | null
  followemail?: boolean | null
  followemailname?: unknown
  ftpsiteurl?: string | null
  importsequencenumber?: number | null
  industrycode?: number | null
  industrycodename?: unknown
  isprivate?: boolean | null
  isprivatename?: unknown
  lastonholdtime?: string | null
  lastusedincampaign?: string | null
  marketcap?: number | null
  marketcap_base?: number | null
  marketingonly?: boolean | null
  marketingonlyname?: unknown
  masteraccountidname?: string | null
  masteraccountidyominame?: string | null
  masterid?: string | null
  merged?: boolean | null
  mergedname?: unknown
  modifiedby?: string | null
  modifiedbyexternalparty?: string | null
  modifiedbyexternalpartyname?: string | null
  modifiedbyexternalpartyyominame?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  msa_managingpartnerid?: string | null
  msa_managingpartneridname?: string | null
  msa_managingpartneridyominame?: string | null
  msdyn_accountkpiid?: string | null
  msdyn_accountkpiidname?: string | null
  msdyn_billingaccount?: string | null
  msdyn_billingaccountname?: string | null
  msdyn_billingaccountyominame?: string | null
  msdyn_gdproptout?: boolean | null
  msdyn_gdproptoutname?: unknown
  msdyn_preferredresource?: string | null
  msdyn_preferredresourcename?: string | null
  msdyn_primarytimezone?: number | null
  msdyn_salesaccelerationinsightid?: string | null
  msdyn_salesaccelerationinsightidname?: string | null
  msdyn_salestaxcode?: string | null
  msdyn_salestaxcodename?: string | null
  msdyn_segmentid?: string | null
  msdyn_segmentidname?: string | null
  msdyn_serviceterritory?: string | null
  msdyn_serviceterritoryname?: string | null
  msdyn_taxexempt?: boolean | null
  msdyn_taxexemptname?: unknown
  msdyn_taxexemptnumber?: string | null
  msdyn_travelcharge?: number | null
  msdyn_travelcharge_base?: number | null
  msdyn_travelchargetype?: number | null
  msdyn_travelchargetypename?: unknown
  msdyn_workhourtemplate?: string | null
  msdyn_workhourtemplatename?: string | null
  msdyn_workorderinstructions?: string | null
  name?: string | null
  numberofemployees?: number | null
  onholdtime?: number | null
  opendeals?: number | null
  opendeals_date?: string | null
  opendeals_state?: number | null
  openrevenue?: number | null
  openrevenue_base?: number | null
  openrevenue_date?: string | null
  openrevenue_state?: number | null
  originatingleadid?: string | null
  originatingleadidname?: string | null
  originatingleadidyominame?: string | null
  overriddencreatedon?: string | null
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  ownershipcode?: number | null
  ownershipcodename?: unknown
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null
  parentaccountid?: string | null
  parentaccountidname?: string | null
  parentaccountidyominame?: string | null
  participatesinworkflow?: boolean | null
  participatesinworkflowname?: unknown
  paymenttermscode?: number | null
  paymenttermscodename?: unknown
  preferredappointmentdaycode?: number | null
  preferredappointmentdaycodename?: unknown
  preferredappointmenttimecode?: number | null
  preferredappointmenttimecodename?: unknown
  preferredcontactmethodcode?: number | null
  preferredcontactmethodcodename?: unknown
  preferredequipmentid?: string | null
  preferredequipmentidname?: string | null
  preferredserviceid?: string | null
  preferredserviceidname?: string | null
  preferredsystemuserid?: string | null
  preferredsystemuseridname?: string | null
  preferredsystemuseridyominame?: string | null
  primarycontactid?: string | null
  primarycontactidname?: string | null
  primarycontactidyominame?: string | null
  primarysatoriid?: string | null
  primarytwitterid?: string | null
  processid?: string | null
  ps_accounttype?: number | null
  ps_accounttypename?: unknown
  ps_classification?: unknown
  ps_classificationname?: unknown
  ps_clientstatus?: string | null
  ps_clientstatusguid?: string | null
  ps_clientstatusname?: string | null
  ps_clienttype?: number | null
  ps_clienttypename?: unknown
  ps_companylogo?: unknown
  ps_companylogo_timestamp?: number | null
  ps_companylogo_url?: string | null
  ps_companylogoid?: string | null
  ps_industry?: string | null
  ps_industryname?: string | null
  ps_initiationdate?: string | null
  ps_language?: string | null
  ps_languagename?: string | null
  ps_leadstage?: string | null
  ps_leadstagename?: string | null
  ps_logo?: unknown
  ps_logo_timestamp?: number | null
  ps_logo_url?: string | null
  ps_logoid?: string | null
  ps_paymentterms?: string | null
  ps_paymenttermsday?: number | null
  ps_paymenttermsname?: string | null
  ps_paymenttermsoption?: number | null
  ps_paymenttermsoptionname?: unknown
  ps_primarysite?: string | null
  ps_primarysitename?: string | null
  ps_rating?: number | null
  ps_ratingstar?: string | null
  ps_recordtype?: number | null
  ps_recordtypename?: unknown
  ps_relationshiptypechoicefield?: unknown
  ps_relationshiptypechoicefieldname?: unknown
  ps_searchtext?: string | null
  ps_sharepointfolder?: string | null
  ps_sharepointfolderid?: number | null
  ps_simproid?: number | null
  ps_simproidno?: number | null
  ps_simprojsonreference?: string | null
  ps_staff?: string | null
  ps_staffname?: string | null
  ps_usexeroforthisaccount?: boolean | null
  ps_usexeroforthisaccountname?: unknown
  ps_xerobalanceoutstanding?: number | null
  ps_xerobalanceoutstanding_base?: number | null
  ps_xerobalanceoverdue?: number | null
  ps_xerobalanceoverdue_base?: number | null
  ps_xeroid?: string | null
  ps_xerojsonreference?: string | null
  revenue?: number | null
  revenue_base?: number | null
  sharesoutstanding?: number | null
  shippingmethodcode?: number | null
  shippingmethodcodename?: unknown
  sic?: string | null
  slaid?: string | null
  slainvokedid?: string | null
  slainvokedidname?: string | null
  slaname?: string | null
  stageid?: string | null
  statecode?: number | null
  statecodename?: unknown
  statuscode?: number | null
  statuscodename?: unknown
  stockexchange?: string | null
  teamsfollowed?: number | null
  telephone1?: string | null
  telephone2?: string | null
  telephone3?: string | null
  territorycode?: number | null
  territorycodename?: unknown
  territoryid?: string | null
  territoryidname?: string | null
  tickersymbol?: string | null
  timespentbymeonemailandmeetings?: string | null
  timezoneruleversionnumber?: number | null
  transactioncurrencyid?: string | null
  transactioncurrencyidname?: string | null
  traversedpath?: string | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null
  websiteurl?: string | null
  yominame?: string | null


  // Relationships
  accountparentaccount?: Account[]
  accountmasteraccount?: Account[]
  msaaccountmanagingpartner?: Account[]
  customerid_account?: Salesorder[]
  ps_AssetManager?: PsVehicledatabase[]
  ps_Client?: Salesorder[]
  ps_Supplier?: Product[]
  msdyn_billingaccount_account?: Account[]
  msdyn_defaultvendor?: Product[]
  msdyn_account?: Salesorder[]
  ps_AccountClassification?: PsSetting[]
  ps_RelationshipType?: PsSetting[]
}

export type AccountEntitySet = 'accounts'

export type AccountCreate = Omit<Account, 'accountid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type AccountUpdate = Partial<Omit<Account, 'accountid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type AccountSelect = keyof Account
export type AccountExpand = {
  accountparentaccount?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  accountmasteraccount?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  msaaccountmanagingpartner?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  customerid_account?: {
    select?: SalesorderSelect[]
    expand?: SalesorderExpand
  }
  ps_AssetManager?: {
    select?: PsVehicledatabaseSelect[]
    expand?: PsVehicledatabaseExpand
  }
  ps_Client?: {
    select?: SalesorderSelect[]
    expand?: SalesorderExpand
  }
  ps_Supplier?: {
    select?: ProductSelect[]
    expand?: ProductExpand
  }
  msdyn_billingaccount_account?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  msdyn_defaultvendor?: {
    select?: ProductSelect[]
    expand?: ProductExpand
  }
  msdyn_account?: {
    select?: SalesorderSelect[]
    expand?: SalesorderExpand
  }
  ps_AccountClassification?: {
    select?: PsSettingSelect[]
    expand?: PsSettingExpand
  }
  ps_RelationshipType?: {
    select?: PsSettingSelect[]
    expand?: PsSettingExpand
  }
}

export const psdeliveryroutesEntitySet: PsDeliveryroutesEntitySet = 'ps_deliveryrouteses'
export const psdeliveryscheduleEntitySet: PsDeliveryscheduleEntitySet = 'ps_deliveryschedules'
export const psjobassetattachmentEntitySet: PsJobassetattachmentEntitySet = 'ps_jobassetattachments'
export const salesorderEntitySet: SalesorderEntitySet = 'salesorders'
export const salesorderdetailEntitySet: SalesorderdetailEntitySet = 'salesorderdetails'
export const pspostalareaboundaryEntitySet: PsPostalareaboundaryEntitySet = 'ps_postalareaboundaries'
export const psrelatedassetEntitySet: PsRelatedassetEntitySet = 'ps_relatedassets'
export const pssettingEntitySet: PsSettingEntitySet = 'ps_settings'
export const psterritorygroupEntitySet: PsTerritorygroupEntitySet = 'ps_territorygroups'
export const psvehicledatabaseEntitySet: PsVehicledatabaseEntitySet = 'ps_vehicledatabases'
export const psstaffEntitySet: PsStaffEntitySet = 'ps_staffs'
export const productEntitySet: ProductEntitySet = 'products'
export const accountEntitySet: AccountEntitySet = 'accounts'
// Entity Set Constants
export const EntitySets = {
  psdeliveryroutes: 'ps_deliveryrouteses' as const,
  psdeliveryschedule: 'ps_deliveryschedules' as const,
  psjobassetattachment: 'ps_jobassetattachments' as const,
  salesorder: 'salesorders' as const,
  salesorderdetail: 'salesorderdetails' as const,
  pspostalareaboundary: 'ps_postalareaboundaries' as const,
  psrelatedasset: 'ps_relatedassets' as const,
  pssetting: 'ps_settings' as const,
  psterritorygroup: 'ps_territorygroups' as const,
  psvehicledatabase: 'ps_vehicledatabases' as const,
  psstaff: 'ps_staffs' as const,
  product: 'products' as const,
  account: 'accounts' as const,
} as const

// Union type of all generated types
export type DataverseEntity = PsDeliveryroutes |
  PsDeliveryschedule |
  PsJobassetattachment |
  Salesorder |
  Salesorderdetail |
  PsPostalareaboundary |
  PsRelatedasset |
  PsSetting |
  PsTerritorygroup |
  PsVehicledatabase |
  PsStaff |
  Product |
  Account
