/**
 * Auto-generated Dataverse Types
 * Generated on: 2026-01-18T11:18:04.224Z
 * 
 * This file is automatically generated. Do not edit manually.
 */

/**
 * Account
 * Business that represents a customer or potential customer. The company that is billed in business transactions.
 */
export interface Account {
  accountid?: string
  accountcategorycode?: number | null
  accountcategorycodename?: unknown
  accountclassificationcode?: number | null
  accountclassificationcodename?: unknown
  accountnumber?: string | null
  accountratingcode?: number | null
  accountratingcodename?: unknown
  address1_addressid?: string | null
  address1_addresstypecode?: number | null
  address1_addresstypecodename?: unknown
  address1_city?: string | null
  address1_composite?: string | null
  address1_country?: string | null
  address1_county?: string | null
  address1_fax?: string | null
  address1_freighttermscode?: number | null
  address1_freighttermscodename?: unknown
  address1_latitude?: number | null
  address1_line1?: string | null
  address1_line2?: string | null
  address1_line3?: string | null
  address1_longitude?: number | null
  address1_name?: string | null
  address1_postalcode?: string | null
  address1_postofficebox?: string | null
  address1_primarycontactname?: string | null
  address1_shippingmethodcode?: number | null
  address1_shippingmethodcodename?: unknown
  address1_stateorprovince?: string | null
  address1_telephone1?: string | null
  address1_telephone2?: string | null
  address1_telephone3?: string | null
  address1_upszone?: string | null
  address1_utcoffset?: number | null
  address2_addressid?: string | null
  address2_addresstypecode?: number | null
  address2_addresstypecodename?: unknown
  address2_city?: string | null
  address2_composite?: string | null
  address2_country?: string | null
  address2_county?: string | null
  address2_fax?: string | null
  address2_freighttermscode?: number | null
  address2_freighttermscodename?: unknown
  address2_latitude?: number | null
  address2_line1?: string | null
  address2_line2?: string | null
  address2_line3?: string | null
  address2_longitude?: number | null
  address2_name?: string | null
  address2_postalcode?: string | null
  address2_postofficebox?: string | null
  address2_primarycontactname?: string | null
  address2_shippingmethodcode?: number | null
  address2_shippingmethodcodename?: unknown
  address2_stateorprovince?: string | null
  address2_telephone1?: string | null
  address2_telephone2?: string | null
  address2_telephone3?: string | null
  address2_upszone?: string | null
  address2_utcoffset?: number | null
  adx_createdbyipaddress?: string | null
  adx_createdbyusername?: string | null
  adx_modifiedbyipaddress?: string | null
  adx_modifiedbyusername?: string | null
  aging30?: number | null
  aging30_base?: number | null
  aging60?: number | null
  aging60_base?: number | null
  aging90?: number | null
  aging90_base?: number | null
  businesstypecode?: number | null
  businesstypecodename?: unknown
  crd47_abn?: string | null
  crd47_accountmanager?: string | null
  crd47_accountmanagername?: string | null
  crd47_engagementdate?: string | null
  crd47_sharepointid?: number | null
  crd47_sharepointname?: string | null
  crd47_shortname?: string | null
  createdby?: string | null
  createdbyexternalparty?: string | null
  createdbyexternalpartyname?: string | null
  createdbyexternalpartyyominame?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  creditlimit?: number | null
  creditlimit_base?: number | null
  creditonhold?: boolean | null
  creditonholdname?: unknown
  customersizecode?: number | null
  customersizecodename?: unknown
  customertypecode?: number | null
  customertypecodename?: unknown
  defaultpricelevelid?: string | null
  defaultpricelevelidname?: string | null
  description?: string | null
  donotbulkemail?: boolean | null
  donotbulkemailname?: unknown
  donotbulkpostalmail?: boolean | null
  donotbulkpostalmailname?: unknown
  donotemail?: boolean | null
  donotemailname?: unknown
  donotfax?: boolean | null
  donotfaxname?: unknown
  donotphone?: boolean | null
  donotphonename?: unknown
  donotpostalmail?: boolean | null
  donotpostalmailname?: unknown
  donotsendmarketingmaterialname?: unknown
  donotsendmm?: boolean | null
  emailaddress1?: string | null
  emailaddress2?: string | null
  emailaddress3?: string | null
  entityimage?: unknown
  entityimage_timestamp?: number | null
  entityimage_url?: string | null
  entityimageid?: string | null
  exchangerate?: number | null
  fax?: string | null
  followemail?: boolean | null
  followemailname?: unknown
  ftpsiteurl?: string | null
  importsequencenumber?: number | null
  industrycode?: number | null
  industrycodename?: unknown
  isprivate?: boolean | null
  isprivatename?: unknown
  lastonholdtime?: string | null
  lastusedincampaign?: string | null
  marketcap?: number | null
  marketcap_base?: number | null
  marketingonly?: boolean | null
  marketingonlyname?: unknown
  masteraccountidname?: string | null
  masteraccountidyominame?: string | null
  masterid?: string | null
  merged?: boolean | null
  mergedname?: unknown
  modifiedby?: string | null
  modifiedbyexternalparty?: string | null
  modifiedbyexternalpartyname?: string | null
  modifiedbyexternalpartyyominame?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  msa_managingpartnerid?: string | null
  msa_managingpartneridname?: string | null
  msa_managingpartneridyominame?: string | null
  msdyn_accountkpiid?: string | null
  msdyn_accountkpiidname?: string | null
  msdyn_billingaccount?: string | null
  msdyn_billingaccountname?: string | null
  msdyn_billingaccountyominame?: string | null
  msdyn_gdproptout?: boolean | null
  msdyn_gdproptoutname?: unknown
  msdyn_preferredresource?: string | null
  msdyn_preferredresourcename?: string | null
  msdyn_primarytimezone?: number | null
  msdyn_salesaccelerationinsightid?: string | null
  msdyn_salesaccelerationinsightidname?: string | null
  msdyn_salestaxcode?: string | null
  msdyn_salestaxcodename?: string | null
  msdyn_segmentid?: string | null
  msdyn_segmentidname?: string | null
  msdyn_serviceterritory?: string | null
  msdyn_serviceterritoryname?: string | null
  msdyn_taxexempt?: boolean | null
  msdyn_taxexemptname?: unknown
  msdyn_taxexemptnumber?: string | null
  msdyn_travelcharge?: number | null
  msdyn_travelcharge_base?: number | null
  msdyn_travelchargetype?: number | null
  msdyn_travelchargetypename?: unknown
  msdyn_workhourtemplate?: string | null
  msdyn_workhourtemplatename?: string | null
  msdyn_workorderinstructions?: string | null
  name?: string | null
  numberofemployees?: number | null
  onholdtime?: number | null
  opendeals?: number | null
  opendeals_date?: string | null
  opendeals_state?: number | null
  openrevenue?: number | null
  openrevenue_base?: number | null
  openrevenue_date?: string | null
  openrevenue_state?: number | null
  originatingleadid?: string | null
  originatingleadidname?: string | null
  originatingleadidyominame?: string | null
  overriddencreatedon?: string | null
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  ownershipcode?: number | null
  ownershipcodename?: unknown
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null
  parentaccountid?: string | null
  parentaccountidname?: string | null
  parentaccountidyominame?: string | null
  participatesinworkflow?: boolean | null
  participatesinworkflowname?: unknown
  paymenttermscode?: number | null
  paymenttermscodename?: unknown
  preferredappointmentdaycode?: number | null
  preferredappointmentdaycodename?: unknown
  preferredappointmenttimecode?: number | null
  preferredappointmenttimecodename?: unknown
  preferredcontactmethodcode?: number | null
  preferredcontactmethodcodename?: unknown
  preferredequipmentid?: string | null
  preferredequipmentidname?: string | null
  preferredserviceid?: string | null
  preferredserviceidname?: string | null
  preferredsystemuserid?: string | null
  preferredsystemuseridname?: string | null
  preferredsystemuseridyominame?: string | null
  primarycontactid?: string | null
  primarycontactidname?: string | null
  primarycontactidyominame?: string | null
  primarysatoriid?: string | null
  primarytwitterid?: string | null
  processid?: string | null
  ps_accounttype?: number | null
  ps_accounttypename?: unknown
  ps_classification?: unknown
  ps_classificationname?: unknown
  ps_clientstatus?: string | null
  ps_clientstatusguid?: string | null
  ps_clientstatusname?: string | null
  ps_clienttype?: number | null
  ps_clienttypename?: unknown
  ps_companylogo?: unknown
  ps_companylogo_timestamp?: number | null
  ps_companylogo_url?: string | null
  ps_companylogoid?: string | null
  ps_industry?: string | null
  ps_industryname?: string | null
  ps_initiationdate?: string | null
  ps_language?: string | null
  ps_languagename?: string | null
  ps_leadstage?: string | null
  ps_leadstagename?: string | null
  ps_logo?: unknown
  ps_logo_timestamp?: number | null
  ps_logo_url?: string | null
  ps_logoid?: string | null
  ps_paymentterms?: string | null
  ps_paymenttermsday?: number | null
  ps_paymenttermsname?: string | null
  ps_paymenttermsoption?: number | null
  ps_paymenttermsoptionname?: unknown
  ps_primarysite?: string | null
  ps_primarysitename?: string | null
  ps_rating?: number | null
  ps_ratingstar?: string | null
  ps_recordtype?: number | null
  ps_recordtypename?: unknown
  ps_relationshiptypechoicefield?: unknown
  ps_relationshiptypechoicefieldname?: unknown
  ps_searchtext?: string | null
  ps_sharepointfolder?: string | null
  ps_sharepointfolderid?: number | null
  ps_simproid?: number | null
  ps_simproidno?: number | null
  ps_simprojsonreference?: string | null
  ps_staff?: string | null
  ps_staffname?: string | null
  ps_usexeroforthisaccount?: boolean | null
  ps_usexeroforthisaccountname?: unknown
  ps_xerobalanceoutstanding?: number | null
  ps_xerobalanceoutstanding_base?: number | null
  ps_xerobalanceoverdue?: number | null
  ps_xerobalanceoverdue_base?: number | null
  ps_xeroid?: string | null
  ps_xerojsonreference?: string | null
  revenue?: number | null
  revenue_base?: number | null
  sharesoutstanding?: number | null
  shippingmethodcode?: number | null
  shippingmethodcodename?: unknown
  sic?: string | null
  slaid?: string | null
  slainvokedid?: string | null
  slainvokedidname?: string | null
  slaname?: string | null
  stageid?: string | null
  statecode?: number | null
  statecodename?: unknown
  statuscode?: number | null
  statuscodename?: unknown
  stockexchange?: string | null
  teamsfollowed?: number | null
  telephone1?: string | null
  telephone2?: string | null
  telephone3?: string | null
  territorycode?: number | null
  territorycodename?: unknown
  territoryid?: string | null
  territoryidname?: string | null
  tickersymbol?: string | null
  timespentbymeonemailandmeetings?: string | null
  timezoneruleversionnumber?: number | null
  transactioncurrencyid?: string | null
  transactioncurrencyidname?: string | null
  traversedpath?: string | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null
  websiteurl?: string | null
  yominame?: string | null


  // Relationships
  accountparentaccount?: Account[]
  accountmasteraccount?: Account[]
  msaaccountmanagingpartner?: Account[]
  msdyn_billingaccount_account?: Account[]
}

export type AccountEntitySet = 'accounts'

export type AccountCreate = Omit<Account, 'accountid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type AccountUpdate = Partial<Omit<Account, 'accountid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type AccountSelect = keyof Account
export type AccountExpand = {
  accountparentaccount?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  accountmasteraccount?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  msaaccountmanagingpartner?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
  msdyn_billingaccount_account?: {
    select?: AccountSelect[]
    expand?: AccountExpand
  }
}

export const accountEntitySet: AccountEntitySet = 'accounts'
// Entity Set Constants
export const EntitySets = {
  account: 'accounts' as const,
} as const

// Union type of all generated types
export type DataverseEntity = Account
