/**
 * Auto-generated Dataverse Types
 * Generated on: 2026-01-18T18:04:10.321Z
 * 
 * This file is automatically generated. Do not edit manually.
 */

/**
 * Delivery Routes
 * Table: ps_deliveryroutes
 */
export interface PsDeliveryroutes {
  ps_deliveryroutesid?: string
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null
  ps_sequence?: number | null
  ps_sitelat?: number | null
  ps_sitelong?: number | null
  ps_vehiclename?: string | null
  statecode?: number | null
  statecodename?: unknown
  statuscode?: number | null
  statuscodename?: unknown
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null
}

export type PsDeliveryroutesEntitySet = 'ps_deliveryrouteses'

export type PsDeliveryroutesCreate = Omit<PsDeliveryroutes, 'ps_deliveryroutesid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsDeliveryroutesUpdate = Partial<Omit<PsDeliveryroutes, 'ps_deliveryroutesid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsDeliveryroutesSelect = keyof PsDeliveryroutes
export type PsDeliveryroutesExpand = Record<string, never>

/**
 * Delivery Schedule
 * Table: ps_deliveryschedule
 */
export interface PsDeliveryschedule {
  ps_deliveryscheduleid?: string
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null
  ps_date?: string | null
  ps_id?: string | null
  ps_operator?: string | null
  ps_operatorname?: string | null
  ps_orderterritory?: string | null
  ps_orderterritoryname?: string | null
  ps_territorygroup?: string | null
  ps_territorygroupname?: string | null
  ps_territorytype?: number | null
  ps_territorytypename?: unknown
  ps_time?: string | null
  ps_vehicle?: string | null
  ps_vehiclename?: string | null
  statecode?: number | null
  statecodename?: unknown
  statuscode?: number | null
  statuscodename?: unknown
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null
}

export type PsDeliveryscheduleEntitySet = 'ps_deliveryschedules'

export type PsDeliveryscheduleCreate = Omit<PsDeliveryschedule, 'ps_deliveryscheduleid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsDeliveryscheduleUpdate = Partial<Omit<PsDeliveryschedule, 'ps_deliveryscheduleid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsDeliveryscheduleSelect = keyof PsDeliveryschedule
export type PsDeliveryscheduleExpand = Record<string, never>

/**
 * Job Asset Attachment
 * Table: ps_jobassetattachment
 */
export interface PsJobassetattachment {
  ps_jobassetattachmentid?: string
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null
  ps_assetnickname?: string | null
  ps_attachment?: string | null
  ps_attachmentid?: string | null
  ps_attachmentname?: string | null
  ps_id?: string | null
  ps_jobschedule?: string | null
  ps_jobscheduledate?: string | null
  ps_jobschedulename?: string | null
  statecode?: number | null
  statecodename?: unknown
  statuscode?: number | null
  statuscodename?: unknown
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null
}

export type PsJobassetattachmentEntitySet = 'ps_jobassetattachments'

export type PsJobassetattachmentCreate = Omit<PsJobassetattachment, 'ps_jobassetattachmentid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsJobassetattachmentUpdate = Partial<Omit<PsJobassetattachment, 'ps_jobassetattachmentid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsJobassetattachmentSelect = keyof PsJobassetattachment
export type PsJobassetattachmentExpand = Record<string, never>

/**
 * Order
 * Quote that has been accepted.
 */
export interface Salesorder {
  salesorderid?: string
  accountid?: string | null
  accountidname?: string | null
  accountidyominame?: string | null
  billto_addressid?: string | null
  billto_city?: string | null
  billto_composite?: string | null
  billto_contactname?: string | null
  billto_country?: string | null
  billto_fax?: string | null
  billto_line1?: string | null
  billto_line2?: string | null
  billto_line3?: string | null
  billto_name?: string | null
  billto_postalcode?: string | null
  billto_stateorprovince?: string | null
  billto_telephone?: string | null
  campaignid?: string | null
  campaignidname?: string | null
  contactid?: string | null
  contactidname?: string | null
  contactidyominame?: string | null
  crd47_clientname?: string | null
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  customerid?: string | null
  customeridname?: string | null
  customeridtype?: string | null
  customeridyominame?: string | null
  datefulfilled?: string | null
  description?: string | null
  discountamount?: number | null
  discountamount_base?: number | null
  discountpercentage?: number | null
  emailaddress?: string | null
  entityimage?: unknown
  entityimage_timestamp?: number | null
  entityimage_url?: string | null
  entityimageid?: string | null
  exchangerate?: number | null
  freightamount?: number | null
  freightamount_base?: number | null
  freighttermscode?: number | null
  freighttermscodename?: unknown
  importsequencenumber?: number | null
  ispricelocked?: boolean | null
  ispricelockedname?: unknown
  lastbackofficesubmit?: string | null
  lastonholdtime?: string | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  msdyn_account?: string | null
  msdyn_accountname?: string | null
  msdyn_accountyominame?: string | null
  msdyn_ordertype?: number | null
  msdyn_ordertypename?: unknown
  msdyn_processstartedon?: string | null
  name?: string | null
  onholdtime?: number | null
  opportunityid?: string | null
  opportunityidname?: string | null
  ordercreationmethod?: number | null
  ordercreationmethodname?: unknown
  ordernumber?: string | null
  overriddencreatedon?: string | null
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null
  paymenttermscode?: number | null
  paymenttermscodename?: unknown
  pricelevelid?: string | null
  pricelevelidname?: string | null
  pricingerrorcode?: number | null
  pricingerrorcodename?: unknown
  prioritycode?: number | null
  prioritycodename?: unknown
  processid?: string | null
  ps_additionalinformation?: string | null
  ps_additionalnotes?: string | null
  ps_client?: string | null
  ps_clientguid?: string | null
  ps_clientname?: string | null
  ps_clientyominame?: string | null
  ps_days?: unknown
  ps_daysname?: unknown
  ps_deliveryinstruction?: string | null
  ps_frequency?: number | null
  ps_frequencyname?: unknown
  ps_keycontact?: string | null
  ps_keycontactname?: string | null
  ps_keycontactyominame?: string | null
  ps_ordersite?: string | null
  ps_ordersitename?: string | null
  ps_orderstatus?: number | null
  ps_orderstatusname?: unknown
  ps_proofofdelivery?: unknown
  ps_proofofdelivery_timestamp?: number | null
  ps_proofofdelivery_url?: string | null
  ps_proofofdeliveryid?: string | null
  ps_setvalidtodate?: boolean | null
  ps_setvalidtodatename?: unknown
  ps_shiptolatitude?: number | null
  ps_shiptolongitude?: number | null
  ps_validfrom?: string | null
  ps_validto?: string | null
  ps_weeklyorder?: string | null
  ps_weeklyordername?: string | null
  quoteid?: string | null
  quoteidname?: string | null
  requestdeliveryby?: string | null
  shippingmethodcode?: number | null
  shippingmethodcodename?: unknown
  shipto_addressid?: string | null
  shipto_city?: string | null
  shipto_composite?: string | null
  shipto_contactname?: string | null
  shipto_country?: string | null
  shipto_fax?: string | null
  shipto_freighttermscode?: number | null
  shipto_freighttermscodename?: unknown
  shipto_line1?: string | null
  shipto_line2?: string | null
  shipto_line3?: string | null
  shipto_name?: string | null
  shipto_postalcode?: string | null
  shipto_stateorprovince?: string | null
  shipto_telephone?: string | null
  skippricecalculation?: number | null
  skippricecalculationname?: unknown
  slaid?: string | null
  slainvokedid?: string | null
  slainvokedidname?: string | null
  slaname?: string | null
  stageid?: string | null
  statecode?: number | null
  statecodename?: unknown
  statuscode?: number | null
  statuscodename?: unknown
  submitdate?: string | null
  submitstatus?: number | null
  submitstatusdescription?: string | null
  timezoneruleversionnumber?: number | null
  totalamount?: number | null
  totalamount_base?: number | null
  totalamountlessfreight?: number | null
  totalamountlessfreight_base?: number | null
  totaldiscountamount?: number | null
  totaldiscountamount_base?: number | null
  totallineitemamount?: number | null
  totallineitemamount_base?: number | null
  totallineitemdiscountamount?: number | null
  totallineitemdiscountamount_base?: number | null
  totaltax?: number | null
  totaltax_base?: number | null
  transactioncurrencyid?: string | null
  transactioncurrencyidname?: string | null
  traversedpath?: string | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null
  willcall?: boolean | null
  willcallname?: unknown


  // Relationships
  orderdetails?: Salesorderdetail[]
}

export type SalesorderEntitySet = 'salesorders'

export type SalesorderCreate = Omit<Salesorder, 'salesorderid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type SalesorderUpdate = Partial<Omit<Salesorder, 'salesorderid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type SalesorderSelect = keyof Salesorder
export type SalesorderExpand = {
  orderdetails?: {
    select?: SalesorderdetailSelect[]
    expand?: SalesorderdetailExpand
  }
}

/**
 * Order Line
 * Line item in a sales order.
 */
export interface Salesorderdetail {
  salesorderdetailid?: string
  baseamount?: number | null
  baseamount_base?: number | null
  crd47_ordervalidfrom?: string | null
  crd47_ordervalidto?: string | null
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  description?: string | null
  exchangerate?: number | null
  extendedamount?: number | null
  extendedamount_base?: number | null
  importsequencenumber?: number | null
  iscopied?: boolean | null
  iscopiedname?: unknown
  ispriceoverridden?: boolean | null
  ispriceoverriddenname?: unknown
  isproductoverridden?: boolean | null
  isproductoverriddenname?: unknown
  lineitemnumber?: number | null
  manualdiscountamount?: number | null
  manualdiscountamount_base?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  msdyn_agreement?: string | null
  msdyn_agreementname?: string | null
  msdyn_linetype?: number | null
  msdyn_linetypename?: unknown
  ordercreationmethod?: number | null
  ordercreationmethodname?: unknown
  overriddencreatedon?: string | null
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningteam?: string | null
  owninguser?: string | null
  parentbundleid?: string | null
  parentbundleidref?: string | null
  priceperunit?: number | null
  priceperunit_base?: number | null
  pricingerrorcode?: number | null
  pricingerrorcodename?: unknown
  productassociationid?: string | null
  productdescription?: string | null
  productid?: string | null
  productidname?: string | null
  productname?: string | null
  productnumber?: string | null
  producttypecode?: number | null
  producttypecodename?: unknown
  propertyconfigurationstatus?: number | null
  propertyconfigurationstatusname?: unknown
  ps_friday?: number | null
  ps_monday?: number | null
  ps_ordersitepostalcode?: string | null
  ps_saturday?: number | null
  ps_sunday?: number | null
  ps_thursday?: number | null
  ps_totalweek?: number | null
  ps_tuesday?: number | null
  ps_wednesday?: number | null
  quantity?: number | null
  quantitybackordered?: number | null
  quantitycancelled?: number | null
  quantityshipped?: number | null
  quotedetailid?: string | null
  quotedetailidname?: string | null
  requestdeliveryby?: string | null
  salesorderdetailname?: string | null
  salesorderid?: string | null
  salesorderidname?: string | null
  salesorderispricelocked?: boolean | null
  salesorderispricelockedname?: unknown
  salesorderstatecode?: number | null
  salesorderstatecodename?: unknown
  salesrepid?: string | null
  salesrepidname?: string | null
  salesrepidyominame?: string | null
  sequencenumber?: number | null
  shipto_addressid?: string | null
  shipto_city?: string | null
  shipto_contactname?: string | null
  shipto_country?: string | null
  shipto_fax?: string | null
  shipto_freighttermscode?: number | null
  shipto_freighttermscodename?: unknown
  shipto_line1?: string | null
  shipto_line2?: string | null
  shipto_line3?: string | null
  shipto_name?: string | null
  shipto_postalcode?: string | null
  shipto_stateorprovince?: string | null
  shipto_telephone?: string | null
  skippricecalculation?: number | null
  skippricecalculationname?: unknown
  tax?: number | null
  tax_base?: number | null
  timezoneruleversionnumber?: number | null
  transactioncurrencyid?: string | null
  transactioncurrencyidname?: string | null
  uomid?: string | null
  uomidname?: string | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null
  volumediscountamount?: number | null
  volumediscountamount_base?: number | null
  willcall?: boolean | null
  willcallname?: unknown


  // Relationships
  parentbundleid_salesorderdetail?: Salesorderdetail[]
  parentbundleidref_salesorderdetail?: Salesorderdetail[]
}

export type SalesorderdetailEntitySet = 'salesorderdetails'

export type SalesorderdetailCreate = Omit<Salesorderdetail, 'salesorderdetailid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type SalesorderdetailUpdate = Partial<Omit<Salesorderdetail, 'salesorderdetailid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type SalesorderdetailSelect = keyof Salesorderdetail
export type SalesorderdetailExpand = {
  parentbundleid_salesorderdetail?: {
    select?: SalesorderdetailSelect[]
    expand?: SalesorderdetailExpand
  }
  parentbundleidref_salesorderdetail?: {
    select?: SalesorderdetailSelect[]
    expand?: SalesorderdetailExpand
  }
}

/**
 * Postal Area Boundary
 * Table: ps_postalareaboundary
 */
export interface PsPostalareaboundary {
  ps_postalareaboundaryid?: string
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null
  ps_assignedterritorygroup?: string | null
  ps_assignedterritorygroupname?: string | null
  ps_color?: string | null
  ps_geojson?: string | null
  ps_id?: string | null
  ps_latitude?: number | null
  ps_longitude?: number | null
  ps_postcode?: string | null
  ps_territorygroupcolor?: string | null
  statecode?: number | null
  statecodename?: unknown
  statuscode?: number | null
  statuscodename?: unknown
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null
}

export type PsPostalareaboundaryEntitySet = 'ps_postalareaboundaries'

export type PsPostalareaboundaryCreate = Omit<PsPostalareaboundary, 'ps_postalareaboundaryid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsPostalareaboundaryUpdate = Partial<Omit<PsPostalareaboundary, 'ps_postalareaboundaryid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsPostalareaboundarySelect = keyof PsPostalareaboundary
export type PsPostalareaboundaryExpand = Record<string, never>

/**
 * Related Asset
 * Table: ps_relatedasset
 */
export interface PsRelatedasset {
  ps_relatedassetid?: string
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null
  ps_asset?: string | null
  ps_assetname?: string | null
  ps_name?: string | null
  ps_product?: string | null
  ps_productname?: string | null
  statecode?: number | null
  statecodename?: unknown
  statuscode?: number | null
  statuscodename?: unknown
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null
}

export type PsRelatedassetEntitySet = 'ps_relatedassets'

export type PsRelatedassetCreate = Omit<PsRelatedasset, 'ps_relatedassetid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsRelatedassetUpdate = Partial<Omit<PsRelatedasset, 'ps_relatedassetid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsRelatedassetSelect = keyof PsRelatedasset
export type PsRelatedassetExpand = Record<string, never>

/**
 * Setting
 * Table: ps_setting
 */
export interface PsSetting {
  ps_settingid?: string
  crd47_powerappiconname?: string | null
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  new_url?: string | null
  overriddencreatedon?: string | null
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null
  ps_apparea?: string | null
  ps_checkgroup?: string | null
  ps_checklisttype?: string | null
  ps_contact?: string | null
  ps_emergencycontacttype?: string | null
  ps_fillcolorvalue?: string | null
  ps_isarchived?: boolean | null
  ps_isarchivedname?: unknown
  ps_meetingtab?: unknown
  ps_meetingtabname?: unknown
  ps_name?: string | null
  ps_order?: number | null
  ps_relatedto?: string | null
  ps_settinggroup?: string | null
  ps_settingicon?: unknown
  ps_settingicon_timestamp?: number | null
  ps_settingicon_url?: string | null
  ps_settingiconid?: string | null
  ps_settingtype?: string | null
  ps_textcolorvalue?: string | null
  statecode?: number | null
  statecodename?: unknown
  statuscode?: number | null
  statuscodename?: unknown
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null


  // Relationships
  ps_VehicleStatus?: PsVehicledatabase[]
  ps_VehicleType?: PsVehicledatabase[]
  ps_FuelType?: PsVehicledatabase[]
  ps_OwnershipStatus?: PsVehicledatabase[]
  ps_Location?: PsVehicledatabase[]
  ps_OrderTerritory?: PsTerritorygroup[]
}

export type PsSettingEntitySet = 'ps_settings'

export type PsSettingCreate = Omit<PsSetting, 'ps_settingid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsSettingUpdate = Partial<Omit<PsSetting, 'ps_settingid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsSettingSelect = keyof PsSetting
export type PsSettingExpand = {
  ps_VehicleStatus?: {
    select?: PsVehicledatabaseSelect[]
    expand?: PsVehicledatabaseExpand
  }
  ps_VehicleType?: {
    select?: PsVehicledatabaseSelect[]
    expand?: PsVehicledatabaseExpand
  }
  ps_FuelType?: {
    select?: PsVehicledatabaseSelect[]
    expand?: PsVehicledatabaseExpand
  }
  ps_OwnershipStatus?: {
    select?: PsVehicledatabaseSelect[]
    expand?: PsVehicledatabaseExpand
  }
  ps_Location?: {
    select?: PsVehicledatabaseSelect[]
    expand?: PsVehicledatabaseExpand
  }
  ps_OrderTerritory?: {
    select?: PsTerritorygroupSelect[]
    expand?: PsTerritorygroupExpand
  }
}

/**
 * Territory Group
 * Table: ps_territorygroup
 */
export interface PsTerritorygroup {
  ps_territorygroupid?: string
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null
  ps_color?: string | null
  ps_id?: string | null
  ps_name?: string | null
  ps_orderterritory?: string | null
  ps_orderterritoryname?: string | null
  ps_territory?: string | null
  ps_territoryname?: string | null
  statecode?: number | null
  statecodename?: unknown
  statuscode?: number | null
  statuscodename?: unknown
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null


  // Relationships
  ps_AssignedTerritoryGroup?: PsPostalareaboundary[]
  ps_TerritoryGroup?: PsDeliveryschedule[]
}

export type PsTerritorygroupEntitySet = 'ps_territorygroups'

export type PsTerritorygroupCreate = Omit<PsTerritorygroup, 'ps_territorygroupid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsTerritorygroupUpdate = Partial<Omit<PsTerritorygroup, 'ps_territorygroupid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsTerritorygroupSelect = keyof PsTerritorygroup
export type PsTerritorygroupExpand = {
  ps_AssignedTerritoryGroup?: {
    select?: PsPostalareaboundarySelect[]
    expand?: PsPostalareaboundaryExpand
  }
  ps_TerritoryGroup?: {
    select?: PsDeliveryscheduleSelect[]
    expand?: PsDeliveryscheduleExpand
  }
}

/**
 * Vehicle Database
 * Table: ps_vehicledatabase
 */
export interface PsVehicledatabase {
  ps_vehicledatabaseid?: string
  crd47_name?: string | null
  crd47_namename?: string | null
  createdby?: string | null
  createdbyname?: string | null
  createdbyyominame?: string | null
  createdon?: string | null
  createdonbehalfby?: string | null
  createdonbehalfbyname?: string | null
  createdonbehalfbyyominame?: string | null
  importsequencenumber?: number | null
  modifiedby?: string | null
  modifiedbyname?: string | null
  modifiedbyyominame?: string | null
  modifiedon?: string | null
  modifiedonbehalfby?: string | null
  modifiedonbehalfbyname?: string | null
  modifiedonbehalfbyyominame?: string | null
  overriddencreatedon?: string | null
  ownerid?: string | null
  owneridname?: string | null
  owneridtype?: string | null
  owneridyominame?: string | null
  owningbusinessunit?: string | null
  owningbusinessunitname?: string | null
  owningteam?: string | null
  owninguser?: string | null
  ps_assetmanager?: string | null
  ps_assetmanagername?: string | null
  ps_assetmanageryominame?: string | null
  ps_assettype?: number | null
  ps_assettypename?: unknown
  ps_assignedoperator?: string | null
  ps_assignedoperatorname?: string | null
  ps_barcode?: string | null
  ps_count?: number | null
  ps_currentvalue?: string | null
  ps_enginenumber?: string | null
  ps_fleetcardoffroad?: string | null
  ps_fleetcardonroad?: string | null
  ps_fueltype?: string | null
  ps_fueltypename?: string | null
  ps_hasissue?: boolean | null
  ps_hasissuename?: unknown
  ps_inspectionbooked?: boolean | null
  ps_inspectionbookeddate?: string | null
  ps_inspectionbookedname?: unknown
  ps_inspectiondueby?: string | null
  ps_insurancecompany?: string | null
  ps_iscompanyowned?: boolean | null
  ps_iscompanyownedname?: unknown
  ps_issuedetails?: string | null
  ps_issues?: string | null
  ps_lastservice?: string | null
  ps_location?: string | null
  ps_locationname?: string | null
  ps_make?: string | null
  ps_model?: string | null
  ps_nextservice?: string | null
  ps_nickname?: string | null
  ps_notes?: string | null
  ps_otheroperators?: string | null
  ps_otheroperatorsname?: string | null
  ps_ownershipstatus?: string | null
  ps_ownershipstatusname?: string | null
  ps_plantid?: string | null
  ps_plate?: string | null
  ps_policynumber?: string | null
  ps_purchasedate?: string | null
  ps_purchaseprice?: string | null
  ps_registrationexpirationdate?: string | null
  ps_requireinspection?: boolean | null
  ps_requireinspectionname?: unknown
  ps_scheduledforservice?: boolean | null
  ps_scheduledforservicename?: unknown
  ps_searchvalue?: string | null
  ps_servicedueby?: string | null
  ps_serviceduebykm?: string | null
  ps_tolltag?: string | null
  ps_vehicleimage?: unknown
  ps_vehicleimage_timestamp?: number | null
  ps_vehicleimage_url?: string | null
  ps_vehicleimageid?: string | null
  ps_vehiclestatus?: string | null
  ps_vehiclestatusname?: string | null
  ps_vehicletype?: string | null
  ps_vehicletypename?: string | null
  ps_vinnumber?: string | null
  ps_year?: number | null
  statecode?: number | null
  statecodename?: unknown
  statuscode?: number | null
  statuscodename?: unknown
  timezoneruleversionnumber?: number | null
  utcconversiontimezonecode?: number | null
  versionnumber?: number | null


  // Relationships
  ps_Vehicle?: PsDeliveryschedule[]
  ps_Asset?: PsRelatedasset[]
  ps_Attachment?: PsJobassetattachment[]
}

export type PsVehicledatabaseEntitySet = 'ps_vehicledatabases'

export type PsVehicledatabaseCreate = Omit<PsVehicledatabase, 'ps_vehicledatabaseid' | 'createdon' | 'modifiedon' | 'versionnumber' | 'createdby' | 'modifiedby' | 'ownerid'>
export type PsVehicledatabaseUpdate = Partial<Omit<PsVehicledatabase, 'ps_vehicledatabaseid' | 'createdon' | 'createdby' | 'versionnumber'>>
export type PsVehicledatabaseSelect = keyof PsVehicledatabase
export type PsVehicledatabaseExpand = {
  ps_Vehicle?: {
    select?: PsDeliveryscheduleSelect[]
    expand?: PsDeliveryscheduleExpand
  }
  ps_Asset?: {
    select?: PsRelatedassetSelect[]
    expand?: PsRelatedassetExpand
  }
  ps_Attachment?: {
    select?: PsJobassetattachmentSelect[]
    expand?: PsJobassetattachmentExpand
  }
}

export const psdeliveryroutesEntitySet: PsDeliveryroutesEntitySet = 'ps_deliveryrouteses'
export const psdeliveryscheduleEntitySet: PsDeliveryscheduleEntitySet = 'ps_deliveryschedules'
export const psjobassetattachmentEntitySet: PsJobassetattachmentEntitySet = 'ps_jobassetattachments'
export const salesorderEntitySet: SalesorderEntitySet = 'salesorders'
export const salesorderdetailEntitySet: SalesorderdetailEntitySet = 'salesorderdetails'
export const pspostalareaboundaryEntitySet: PsPostalareaboundaryEntitySet = 'ps_postalareaboundaries'
export const psrelatedassetEntitySet: PsRelatedassetEntitySet = 'ps_relatedassets'
export const pssettingEntitySet: PsSettingEntitySet = 'ps_settings'
export const psterritorygroupEntitySet: PsTerritorygroupEntitySet = 'ps_territorygroups'
export const psvehicledatabaseEntitySet: PsVehicledatabaseEntitySet = 'ps_vehicledatabases'
// Entity Set Constants
export const EntitySets = {
  psdeliveryroutes: 'ps_deliveryrouteses' as const,
  psdeliveryschedule: 'ps_deliveryschedules' as const,
  psjobassetattachment: 'ps_jobassetattachments' as const,
  salesorder: 'salesorders' as const,
  salesorderdetail: 'salesorderdetails' as const,
  pspostalareaboundary: 'ps_postalareaboundaries' as const,
  psrelatedasset: 'ps_relatedassets' as const,
  pssetting: 'ps_settings' as const,
  psterritorygroup: 'ps_territorygroups' as const,
  psvehicledatabase: 'ps_vehicledatabases' as const,
} as const

// Union type of all generated types
export type DataverseEntity = PsDeliveryroutes |
  PsDeliveryschedule |
  PsJobassetattachment |
  Salesorder |
  Salesorderdetail |
  PsPostalareaboundary |
  PsRelatedasset |
  PsSetting |
  PsTerritorygroup |
  PsVehicledatabase
